import 'server-only';import { sql } from 'drizzle-orm';import { appDb,systemDb,type AppTransaction } from '@/db/client';import { users } from '@/db/schema';import { eq } from 'drizzle-orm';import { isVerifiedAppUser,type VerifiedAppUser } from '@/lib/auth/verified-user';import type { UserRole } from '@/types';
export class DatabaseSecurityError extends Error{constructor(message:string){super(message);this.name='DatabaseSecurityError'}}
type RuntimeRole='duta_app'|'duta_system';type RoleRow={role_name:string;superuser:boolean;bypass_rls:boolean;create_role:boolean;create_db:boolean;replication:boolean;owned_tables:number};export type ResolvedDbActor={id:string;role:UserRole;name:string};
const uuidPattern=/^[0-9a-f]{8}-[0-9a-f]{4}-[1-5][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/i;const verifiedRoles=new Map<RuntimeRole,Promise<void>>();
async function assertRestrictedRole(role:RuntimeRole,db:NonNullable<typeof appDb>){let pending=verifiedRoles.get(role);if(!pending){pending=(async()=>{const result=await db.execute(sql<RoleRow>`select current_user::text as role_name,r.rolsuper as superuser,r.rolbypassrls as bypass_rls,r.rolcreaterole as create_role,r.rolcreatedb as create_db,r.rolreplication as replication,(select count(*)::int from pg_class c join pg_namespace n on n.oid=c.relnamespace where n.nspname='public' and c.relowner=r.oid) as owned_tables from pg_roles r where r.rolname=current_user`);const row=result[0];if(!row||row.role_name!==role||row.superuser||row.bypass_rls||row.create_role||row.create_db||row.replication||Number(row.owned_tables)!==0)throw new DatabaseSecurityError(`Unsafe runtime database role: expected ${role}`)})();verifiedRoles.set(role,pending)}try{await pending}catch(error){verifiedRoles.delete(role);throw error}}
export async function withUserTransaction<T>(identity:VerifiedAppUser,work:(tx:AppTransaction,actor:ResolvedDbActor)=>Promise<T>):Promise<T>{if(!appDb)throw new DatabaseSecurityError('APP_DATABASE_URL is not configured');if(!isVerifiedAppUser(identity)||!uuidPattern.test(identity.id))throw new DatabaseSecurityError('Verified application identity is required');await assertRestrictedRole('duta_app',appDb);return appDb.transaction(async tx=>{await tx.execute(sql`select set_config('app.user_id',${identity.id},true)`);const context=await tx.execute<{id:string|null}>(sql`select public.current_app_user_id()::text as id`);if(context[0]?.id!==identity.id)throw new DatabaseSecurityError('Transaction identity mismatch');const rows=await tx.select({id:users.id,role:users.role,name:users.name,suspendedAt:users.suspendedAt}).from(users).where(eq(users.id,identity.id)).limit(1);const profile=rows[0];if(!profile||profile.suspendedAt||profile.role!==identity.role)throw new DatabaseSecurityError('Database authorization profile mismatch');return work(tx,{id:profile.id,role:profile.role,name:profile.name})})}
export async function withPublicTransaction<T>(work:(tx:AppTransaction)=>Promise<T>):Promise<T>{if(!appDb)throw new DatabaseSecurityError('APP_DATABASE_URL is not configured');await assertRestrictedRole('duta_app',appDb);return appDb.transaction(async tx=>{await tx.execute(sql`select set_config('app.user_id','',true)`);return work(tx)})}
export async function withSystemTransaction<T>(operation:string,work:(tx:AppTransaction)=>Promise<T>):Promise<T>{if(!systemDb)throw new DatabaseSecurityError('SYSTEM_DATABASE_URL is not configured');if(!/^[a-z0-9_.:-]{3,80}$/i.test(operation))throw new DatabaseSecurityError('Invalid system operation');await assertRestrictedRole('duta_system',systemDb as NonNullable<typeof appDb>);return systemDb.transaction(async tx=>{await tx.execute(sql`select set_config('app.user_id','',true),set_config('app.system_operation',${operation},true)`);return work(tx as AppTransaction)})}

