-- Day 8K: additive moderation and factual trust foundation. Reports are signals, never verdicts.
DO $$ BEGIN CREATE TYPE public.moderation_case_status AS ENUM ('NORMAL','LIMITED','UNDER_REVIEW','SUSPENDED','BANNED','REGULATORY_HOLD','CLOSED'); EXCEPTION WHEN duplicate_object THEN NULL; END $$;
--> statement-breakpoint
DO $$ BEGIN CREATE TYPE public.moderation_severity AS ENUM ('LOW','MEDIUM','HIGH','CRITICAL'); EXCEPTION WHEN duplicate_object THEN NULL; END $$;
--> statement-breakpoint
DO $$ BEGIN CREATE TYPE public.moderation_scope AS ENUM ('CONTENT_ONLY','MARKETPLACE','EVENTS','JOBS','COMMUNITY_POSTING','ENTITY_ACTIVITY','ACCOUNT'); EXCEPTION WHEN duplicate_object THEN NULL; END $$;
--> statement-breakpoint
CREATE TABLE IF NOT EXISTS public.moderation_cases (id uuid PRIMARY KEY DEFAULT gen_random_uuid(),target_type text NOT NULL,target_id uuid NOT NULL,status public.moderation_case_status NOT NULL DEFAULT 'UNDER_REVIEW',severity public.moderation_severity NOT NULL DEFAULT 'LOW',assigned_reviewer_id uuid REFERENCES public.users(id),decision text,decision_reason text,decided_at timestamptz,reviewed_by uuid REFERENCES public.users(id),created_at timestamptz NOT NULL DEFAULT now(),updated_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE IF NOT EXISTS public.moderation_case_reports (case_id uuid NOT NULL REFERENCES public.moderation_cases(id) ON DELETE CASCADE,report_id uuid NOT NULL REFERENCES public.reports(id) ON DELETE RESTRICT,created_at timestamptz NOT NULL DEFAULT now(),UNIQUE(case_id,report_id));
CREATE TABLE IF NOT EXISTS public.moderation_actions (id uuid PRIMARY KEY DEFAULT gen_random_uuid(),case_id uuid NOT NULL REFERENCES public.moderation_cases(id) ON DELETE RESTRICT,actor_user_id uuid NOT NULL REFERENCES public.users(id),target_type text NOT NULL,target_id uuid NOT NULL,scope public.moderation_scope NOT NULL,old_status public.moderation_case_status,new_status public.moderation_case_status NOT NULL,reason text NOT NULL,created_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE IF NOT EXISTS public.moderation_evidence (id uuid PRIMARY KEY DEFAULT gen_random_uuid(),case_id uuid NOT NULL REFERENCES public.moderation_cases(id) ON DELETE CASCADE,submitted_by uuid REFERENCES public.users(id),storage_key text,note text,created_at timestamptz NOT NULL DEFAULT now());
CREATE INDEX IF NOT EXISTS moderation_case_target_idx ON public.moderation_cases(target_type,target_id,status);
CREATE INDEX IF NOT EXISTS moderation_action_case_idx ON public.moderation_actions(case_id,created_at);
ALTER TABLE public.moderation_cases ENABLE ROW LEVEL SECURITY; ALTER TABLE public.moderation_case_reports ENABLE ROW LEVEL SECURITY; ALTER TABLE public.moderation_actions ENABLE ROW LEVEL SECURITY; ALTER TABLE public.moderation_evidence ENABLE ROW LEVEL SECURITY;
REVOKE ALL ON public.moderation_cases,public.moderation_case_reports,public.moderation_actions,public.moderation_evidence FROM anon,authenticated;
-- Only canonical platform moderation_admin may access investigation material. Reporter identity and evidence remain private.
GRANT SELECT,INSERT,UPDATE ON public.moderation_cases,public.moderation_case_reports,public.moderation_actions,public.moderation_evidence TO duta_app;
CREATE POLICY moderation_cases_admin_only ON public.moderation_cases FOR ALL TO duta_app USING (EXISTS(SELECT 1 FROM public.user_platform_roles r WHERE r.user_id=public.current_app_user_id() AND r.role='moderation_admin' AND r.revoked_at IS NULL)) WITH CHECK (EXISTS(SELECT 1 FROM public.user_platform_roles r WHERE r.user_id=public.current_app_user_id() AND r.role='moderation_admin' AND r.revoked_at IS NULL));
CREATE POLICY moderation_case_reports_admin_only ON public.moderation_case_reports FOR ALL TO duta_app USING (EXISTS(SELECT 1 FROM public.user_platform_roles r WHERE r.user_id=public.current_app_user_id() AND r.role='moderation_admin' AND r.revoked_at IS NULL)) WITH CHECK (EXISTS(SELECT 1 FROM public.user_platform_roles r WHERE r.user_id=public.current_app_user_id() AND r.role='moderation_admin' AND r.revoked_at IS NULL));
CREATE POLICY moderation_actions_admin_read ON public.moderation_actions FOR SELECT TO duta_app USING (EXISTS(SELECT 1 FROM public.user_platform_roles r WHERE r.user_id=public.current_app_user_id() AND r.role='moderation_admin' AND r.revoked_at IS NULL));
CREATE POLICY moderation_actions_admin_append ON public.moderation_actions FOR INSERT TO duta_app WITH CHECK (EXISTS(SELECT 1 FROM public.user_platform_roles r WHERE r.user_id=public.current_app_user_id() AND r.role='moderation_admin' AND r.revoked_at IS NULL));
CREATE POLICY moderation_evidence_admin_only ON public.moderation_evidence FOR ALL TO duta_app USING (EXISTS(SELECT 1 FROM public.user_platform_roles r WHERE r.user_id=public.current_app_user_id() AND r.role='moderation_admin' AND r.revoked_at IS NULL)) WITH CHECK (EXISTS(SELECT 1 FROM public.user_platform_roles r WHERE r.user_id=public.current_app_user_id() AND r.role='moderation_admin' AND r.revoked_at IS NULL));
-- No trigger reads report count or modifies verification, eligibility, legal status, plans, or source provenance.
