-- 0045: additive official representative News editorial foundation.
-- No collection, credentials, backfill, or environment execution is authorized.
BEGIN;
CREATE TYPE public.official_news_risk AS ENUM ('ROUTINE','HIGH_RISK');
CREATE TYPE public.official_news_risk_reason AS ENUM ('PROTECTION','SAFETY','EMERGENCY','LEGAL','IMMIGRATION','EMPLOYMENT_RIGHTS','CRITICAL_CONSULAR_PROCEDURE','DEADLINE_OR_ELIGIBILITY','UNCERTAIN_FACTUAL_SUPPORT');
CREATE TYPE public.official_news_review_state AS ENUM ('DRAFT','VERIFIED_BY_EDITOR','READY_FOR_REVIEW','APPROVED','CHANGES_REQUESTED','REJECTED');
CREATE TYPE public.official_news_publication_state AS ENUM ('DRAFT','PUBLISHED','WITHDRAWN','SUPERSEDED');
CREATE TYPE public.official_news_correction_state AS ENUM ('CURRENT','CORRECTED','WITHDRAWN','SUPERSEDED');
CREATE TYPE public.official_news_collection_mode AS ENUM ('MANUAL_EDITORIAL','OFFICIAL_API','APPROVED_PROVIDER','LINK_ONLY','TEMPORARILY_UNAVAILABLE');
CREATE TYPE public.official_news_retention_class AS ENUM ('PUBLIC_PROVENANCE','EDITORIAL_DRAFT','AI_DRAFT_AUDIT','PUBLICATION_AUDIT','MEDIA_REFERENCE','AUTOMATION_OPERATIONS');
CREATE TYPE public.official_news_event_type AS ENUM ('DRAFT_CREATED','DRAFT_UPDATED','AI_DRAFT_GENERATED','RISK_CLASSIFIED','VERIFIED_BY_EDITOR','SUBMITTED_FOR_REVIEW','APPROVED','CHANGES_REQUESTED','REJECTED','PUBLISHED','SOURCE_REFERENCE_ADDED','DEDUPE_CANDIDATE_IDENTIFIED','MERGED','CORRECTION_STARTED','SUPERSEDED','WITHDRAWN','COLLECTION_CONFIG_CHANGED');
CREATE TABLE public.official_news_stories (
 id uuid PRIMARY KEY DEFAULT gen_random_uuid(), display_title text NOT NULL CHECK(char_length(display_title) BETWEEN 1 AND 240), concise_summary text NOT NULL CHECK(char_length(concise_summary) BETWEEN 1 AND 1200), what_text text NOT NULL CHECK(char_length(what_text) BETWEEN 1 AND 2400), five_w_context jsonb NOT NULL, content_type text NOT NULL CHECK(char_length(content_type) BETWEEN 1 AND 80), risk_classification public.official_news_risk NOT NULL DEFAULT 'ROUTINE', risk_reasons public.official_news_risk_reason[] NOT NULL DEFAULT '{}', review_state public.official_news_review_state NOT NULL DEFAULT 'DRAFT', publication_state public.official_news_publication_state NOT NULL DEFAULT 'DRAFT', correction_state public.official_news_correction_state NOT NULL DEFAULT 'CURRENT', canonical_official_source_id uuid NOT NULL REFERENCES public.official_sources(id) ON DELETE RESTRICT, canonical_url text NOT NULL CHECK(char_length(canonical_url) BETWEEN 1 AND 2048), source_published_at timestamptz, created_by uuid NOT NULL REFERENCES public.users(id) ON DELETE RESTRICT, verified_by uuid REFERENCES public.users(id) ON DELETE RESTRICT, approved_by uuid REFERENCES public.users(id) ON DELETE RESTRICT, published_by uuid REFERENCES public.users(id) ON DELETE RESTRICT, published_at timestamptz, withdrawn_at timestamptz, superseded_by_story_id uuid REFERENCES public.official_news_stories(id) ON DELETE RESTRICT, ai_assisted boolean NOT NULL DEFAULT false, retention_class public.official_news_retention_class NOT NULL DEFAULT 'EDITORIAL_DRAFT', retention_review_at timestamptz, purge_eligible_at timestamptz, created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now(),
 CONSTRAINT official_news_five_w_ck CHECK(jsonb_typeof(five_w_context)='object' AND five_w_context->>'version'='1' AND five_w_context ?& ARRAY['who','where','when','why'] AND (five_w_context->'who'->>'state') IN ('SUPPORTED','NOT_STATED','NOT_MATERIAL') AND (five_w_context->'where'->>'state') IN ('SUPPORTED','NOT_STATED','NOT_MATERIAL') AND (five_w_context->'when'->>'state') IN ('SUPPORTED','NOT_STATED','NOT_MATERIAL') AND (five_w_context->'why'->>'state') IN ('SUPPORTED','NOT_STATED','NOT_MATERIAL')),
 CONSTRAINT official_news_risk_ck CHECK((risk_classification='ROUTINE' AND cardinality(risk_reasons)=0) OR (risk_classification='HIGH_RISK' AND cardinality(risk_reasons)>0)),
 CONSTRAINT official_news_published_ck CHECK(publication_state<>'PUBLISHED' OR (published_at IS NOT NULL AND published_by IS NOT NULL AND (risk_classification='ROUTINE' OR approved_by IS NOT NULL)))
);
CREATE TABLE public.official_news_story_source_references (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), story_id uuid NOT NULL REFERENCES public.official_news_stories(id) ON DELETE RESTRICT, official_source_id uuid NOT NULL REFERENCES public.official_sources(id) ON DELETE RESTRICT, original_url text NOT NULL CHECK(char_length(original_url) BETWEEN 1 AND 2048), canonical_url text NOT NULL CHECK(char_length(canonical_url) BETWEEN 1 AND 2048), external_item_id text CHECK(char_length(external_item_id) BETWEEN 1 AND 512), source_published_at timestamptz, collection_mode public.official_news_collection_mode NOT NULL DEFAULT 'MANUAL_EDITORIAL', intake_idempotency_key uuid, provenance jsonb NOT NULL DEFAULT '{}'::jsonb CHECK(jsonb_typeof(provenance)='object' AND octet_length(provenance::text)<=8192), created_by uuid NOT NULL REFERENCES public.users(id) ON DELETE RESTRICT, created_at timestamptz NOT NULL DEFAULT now(), CONSTRAINT official_news_source_ref_intake_uq UNIQUE(story_id,intake_idempotency_key));
CREATE TABLE public.official_news_events (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), story_id uuid NOT NULL REFERENCES public.official_news_stories(id) ON DELETE RESTRICT, event_type public.official_news_event_type NOT NULL, actor_id uuid REFERENCES public.users(id) ON DELETE RESTRICT, metadata jsonb NOT NULL DEFAULT '{}'::jsonb CHECK(jsonb_typeof(metadata)='object' AND octet_length(metadata::text)<=8192), occurred_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE public.official_news_collection_config (official_source_id uuid PRIMARY KEY REFERENCES public.official_sources(id) ON DELETE RESTRICT, collection_mode public.official_news_collection_mode NOT NULL DEFAULT 'MANUAL_EDITORIAL', enabled boolean NOT NULL DEFAULT false, adapter_name text CHECK(char_length(adapter_name)<=120), adapter_version text CHECK(char_length(adapter_version)<=120), updated_by uuid REFERENCES public.users(id) ON DELETE RESTRICT, updated_at timestamptz NOT NULL DEFAULT now(), CONSTRAINT official_news_manual_only_ck CHECK(collection_mode='MANUAL_EDITORIAL' OR enabled=false));
CREATE TABLE public.official_news_ingestion_runs (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), official_source_id uuid NOT NULL REFERENCES public.official_sources(id) ON DELETE RESTRICT, collection_mode public.official_news_collection_mode NOT NULL, run_state text NOT NULL CHECK(run_state IN ('STARTED','SUCCEEDED','FAILED','SKIPPED')), started_at timestamptz NOT NULL DEFAULT now(), completed_at timestamptz, received_count integer NOT NULL DEFAULT 0 CHECK(received_count>=0), accepted_count integer NOT NULL DEFAULT 0 CHECK(accepted_count>=0), rejected_count integer NOT NULL DEFAULT 0 CHECK(rejected_count>=0), reason_code text CHECK(char_length(reason_code)<=120), metadata jsonb NOT NULL DEFAULT '{}'::jsonb CHECK(jsonb_typeof(metadata)='object' AND octet_length(metadata::text)<=8192));
CREATE INDEX official_news_public_feed_idx ON public.official_news_stories(publication_state,correction_state,published_at DESC);
CREATE INDEX official_news_search_idx ON public.official_news_stories USING gin(to_tsvector('simple',coalesce(display_title,'') || ' ' || coalesce(concise_summary,'') || ' ' || coalesce(what_text,'')));
CREATE INDEX official_news_source_refs_story_idx ON public.official_news_story_source_references(story_id); CREATE INDEX official_news_source_refs_url_idx ON public.official_news_story_source_references(canonical_url); CREATE INDEX official_news_events_story_time_idx ON public.official_news_events(story_id,occurred_at DESC); CREATE INDEX official_news_runs_source_time_idx ON public.official_news_ingestion_runs(official_source_id,started_at DESC);
CREATE OR REPLACE FUNCTION public.enforce_official_news_source_reference() RETURNS trigger LANGUAGE plpgsql SECURITY DEFINER SET search_path='' AS $$ BEGIN IF NOT EXISTS(SELECT 1 FROM public.official_sources source WHERE source.id=NEW.official_source_id AND source.active AND source.source_purpose='NEWS') THEN RAISE EXCEPTION 'official News source must be active and NEWS-purpose'; END IF; RETURN NEW; END $$;
CREATE TRIGGER official_news_source_reference_guard BEFORE INSERT OR UPDATE OF official_source_id ON public.official_news_story_source_references FOR EACH ROW EXECUTE FUNCTION public.enforce_official_news_source_reference();
CREATE OR REPLACE FUNCTION public.transition_official_news_story(target_story uuid, requested_event public.official_news_event_type) RETURNS void LANGUAGE plpgsql SECURITY DEFINER SET search_path='' AS $$
DECLARE story public.official_news_stories%ROWTYPE; actor uuid; editor boolean; moderator boolean;
BEGIN
 actor:=public.current_app_user_id(); IF actor IS NULL THEN RAISE EXCEPTION 'authenticated actor required'; END IF;
 editor:=public.current_app_has_role(ARRAY['EDITOR']::public.user_role[]); moderator:=public.current_app_has_role(ARRAY['MODERATOR','SUPER_ADMIN']::public.user_role[]);
 SELECT * INTO story FROM public.official_news_stories WHERE id=target_story FOR UPDATE; IF NOT FOUND THEN RAISE EXCEPTION 'News story not found'; END IF;
 IF requested_event='VERIFIED_BY_EDITOR' AND editor AND story.risk_classification='ROUTINE' AND story.review_state='DRAFT' THEN UPDATE public.official_news_stories SET review_state='VERIFIED_BY_EDITOR',verified_by=actor,updated_at=now() WHERE id=target_story;
 ELSIF requested_event='SUBMITTED_FOR_REVIEW' AND editor AND story.risk_classification='HIGH_RISK' AND story.review_state IN ('DRAFT','CHANGES_REQUESTED') THEN UPDATE public.official_news_stories SET review_state='READY_FOR_REVIEW',updated_at=now() WHERE id=target_story;
 ELSIF requested_event='APPROVED' AND moderator AND story.risk_classification='HIGH_RISK' AND story.review_state='READY_FOR_REVIEW' THEN UPDATE public.official_news_stories SET review_state='APPROVED',approved_by=actor,updated_at=now() WHERE id=target_story;
 ELSIF requested_event='PUBLISHED' AND (editor OR moderator) AND story.publication_state='DRAFT' AND ((story.risk_classification='ROUTINE' AND story.review_state='VERIFIED_BY_EDITOR') OR (story.risk_classification='HIGH_RISK' AND story.review_state='APPROVED')) AND EXISTS(SELECT 1 FROM public.official_news_story_source_references ref WHERE ref.story_id=target_story) THEN UPDATE public.official_news_stories SET publication_state='PUBLISHED',published_by=actor,published_at=now(),retention_class='PUBLICATION_AUDIT',updated_at=now() WHERE id=target_story;
 ELSIF requested_event='WITHDRAWN' AND moderator AND story.publication_state='PUBLISHED' THEN UPDATE public.official_news_stories SET publication_state='WITHDRAWN',correction_state='WITHDRAWN',withdrawn_at=now(),updated_at=now() WHERE id=target_story;
 ELSIF requested_event='SUPERSEDED' AND moderator AND story.publication_state='PUBLISHED' AND story.superseded_by_story_id IS NOT NULL THEN UPDATE public.official_news_stories SET publication_state='SUPERSEDED',correction_state='SUPERSEDED',updated_at=now() WHERE id=target_story;
 ELSE RAISE EXCEPTION 'requested News transition is not permitted'; END IF;
 INSERT INTO public.official_news_events(story_id,event_type,actor_id) VALUES(target_story,requested_event,actor);
END $$;
ALTER TABLE public.official_news_stories ENABLE ROW LEVEL SECURITY; ALTER TABLE public.official_news_story_source_references ENABLE ROW LEVEL SECURITY; ALTER TABLE public.official_news_events ENABLE ROW LEVEL SECURITY; ALTER TABLE public.official_news_collection_config ENABLE ROW LEVEL SECURITY; ALTER TABLE public.official_news_ingestion_runs ENABLE ROW LEVEL SECURITY;
REVOKE ALL ON public.official_news_stories,public.official_news_story_source_references,public.official_news_events,public.official_news_collection_config,public.official_news_ingestion_runs FROM PUBLIC,anon,authenticated;
GRANT SELECT,INSERT ON public.official_news_stories,public.official_news_story_source_references TO duta_app; GRANT UPDATE (display_title,concise_summary,what_text,five_w_context,content_type) ON public.official_news_stories TO duta_app; GRANT SELECT ON public.official_news_events TO duta_app; GRANT SELECT,INSERT,UPDATE ON public.official_news_collection_config,public.official_news_ingestion_runs TO duta_app;
GRANT EXECUTE ON FUNCTION public.transition_official_news_story(uuid,public.official_news_event_type) TO duta_app;
CREATE POLICY official_news_stories_public_read ON public.official_news_stories FOR SELECT TO duta_app USING(publication_state='PUBLISHED' AND correction_state='CURRENT');
CREATE POLICY official_news_stories_editorial_read ON public.official_news_stories FOR SELECT TO duta_app USING(public.current_app_has_role(ARRAY['EDITOR','MODERATOR','SUPER_ADMIN']::public.user_role[]));
CREATE POLICY official_news_stories_editor_draft ON public.official_news_stories FOR INSERT TO duta_app WITH CHECK(public.current_app_has_role(ARRAY['EDITOR']::public.user_role[]) AND created_by=public.current_app_user_id() AND review_state='DRAFT' AND publication_state='DRAFT');
CREATE POLICY official_news_stories_editor_update_own_draft ON public.official_news_stories FOR UPDATE TO duta_app USING(public.current_app_has_role(ARRAY['EDITOR']::public.user_role[]) AND created_by=public.current_app_user_id() AND review_state='DRAFT' AND publication_state='DRAFT' AND correction_state='CURRENT') WITH CHECK(public.current_app_has_role(ARRAY['EDITOR']::public.user_role[]) AND created_by=public.current_app_user_id() AND review_state='DRAFT' AND publication_state='DRAFT' AND correction_state='CURRENT');
CREATE POLICY official_news_source_refs_public_read ON public.official_news_story_source_references FOR SELECT TO duta_app USING(EXISTS(SELECT 1 FROM public.official_news_stories story WHERE story.id=story_id AND story.publication_state='PUBLISHED' AND story.correction_state='CURRENT'));
CREATE POLICY official_news_source_refs_editorial_read ON public.official_news_story_source_references FOR SELECT TO duta_app USING(public.current_app_has_role(ARRAY['EDITOR','MODERATOR','SUPER_ADMIN']::public.user_role[]));
CREATE POLICY official_news_source_refs_editor_append ON public.official_news_story_source_references FOR INSERT TO duta_app WITH CHECK(public.current_app_has_role(ARRAY['EDITOR']::public.user_role[]) AND created_by=public.current_app_user_id());
CREATE POLICY official_news_events_editorial_read ON public.official_news_events FOR SELECT TO duta_app USING(public.current_app_has_role(ARRAY['EDITOR','MODERATOR','SUPER_ADMIN']::public.user_role[]));
CREATE POLICY official_news_config_super_admin ON public.official_news_collection_config FOR ALL TO duta_app USING(public.current_app_has_role(ARRAY['SUPER_ADMIN']::public.user_role[])) WITH CHECK(public.current_app_has_role(ARRAY['SUPER_ADMIN']::public.user_role[]));
CREATE POLICY official_news_runs_super_admin_read ON public.official_news_ingestion_runs FOR SELECT TO duta_app USING(public.current_app_has_role(ARRAY['SUPER_ADMIN']::public.user_role[]));
COMMIT;
