-- LOCAL_STAGING ONLY — explicit Phase 3 rollback.
BEGIN;
DO $$ BEGIN IF current_database()<>'duta_rantau_staging' THEN RAISE EXCEPTION 'wrong database'; END IF; END $$;
DO $$ BEGIN IF EXISTS(SELECT 1 FROM pg_policies WHERE schemaname='public' AND policyname<>ALL(ARRAY['users_own_select','users_own_update','notifications_own_select','notifications_own_update','ai_own_all','memberships_own_select','payments_own_select','official_sources_public_select','official_offices_public_select','official_contacts_public_select','jobs_public_select','contents_select','communities_select','organizations_select','sellers_select','products_select','events_select','templates_select','evidence_authenticated_select','contents_owner_insert','contents_owner_update','contents_owner_delete','communities_owner_insert','communities_owner_update','communities_owner_delete','sellers_owner_all','products_owner_all','organizations_insert','organizations_update','org_members_select','org_members_first_owner_insert','org_members_admin_insert','org_members_owner_update','org_members_owner_delete','org_permissions_select','org_permissions_manage','org_subscriptions_select','org_payments_select','org_finances_all','org_documents_all','org_meetings_all','org_letters_all','org_attendance_all','org_tasks_all','org_branches_all','publication_projects_all','publication_templates_manage','transcripts_all','community_members_all','reports_insert','reports_select','reports_update','events_manage','official_sources_editor_all','official_offices_editor_all','official_contacts_editor_all','official_evidence_editor_all','audit_super_select','audit_user_insert','sessions_system_all','memberships_system_all','payments_system_all','org_subscriptions_system_all','org_payments_system_all','notifications_system_all','official_sources_system_all','official_offices_system_all','official_contacts_system_all','official_evidence_system_all','audit_system_insert','system_reference_users','system_reference_orgs','system_reference_members','members_self_select','members_admin_select','members_self_insert','members_self_update','members_admin_update','member_phone_challenges_self_all','jobs_admin_all','communities_admin_all','sellers_admin_all','products_admin_all','official_sources_admin_all','organizations_admin_insert','organizations_admin_delete'])) THEN RAISE EXCEPTION 'unexpected non-Phase3 policy detected; rollback stopped'; END IF; END $$;
DROP POLICY IF EXISTS users_own_select ON public.users;
DROP POLICY IF EXISTS users_own_update ON public.users;
DROP POLICY IF EXISTS notifications_own_select ON public.notifications;
DROP POLICY IF EXISTS notifications_own_update ON public.notifications;
DROP POLICY IF EXISTS ai_own_all ON public.ai_conversations;
DROP POLICY IF EXISTS memberships_own_select ON public.memberships;
DROP POLICY IF EXISTS payments_own_select ON public.payments;
DROP POLICY IF EXISTS official_sources_public_select ON public.official_sources;
DROP POLICY IF EXISTS official_offices_public_select ON public.official_offices;
DROP POLICY IF EXISTS official_contacts_public_select ON public.official_contacts;
DROP POLICY IF EXISTS jobs_public_select ON public.jobs;
DROP POLICY IF EXISTS contents_select ON public.contents;
DROP POLICY IF EXISTS communities_select ON public.communities;
DROP POLICY IF EXISTS organizations_select ON public.organizations;
DROP POLICY IF EXISTS sellers_select ON public.sellers;
DROP POLICY IF EXISTS products_select ON public.products;
DROP POLICY IF EXISTS events_select ON public.events;
DROP POLICY IF EXISTS templates_select ON public.publication_templates;
DROP POLICY IF EXISTS evidence_authenticated_select ON public.official_evidence;
DROP POLICY IF EXISTS contents_owner_insert ON public.contents;
DROP POLICY IF EXISTS contents_owner_update ON public.contents;
DROP POLICY IF EXISTS contents_owner_delete ON public.contents;
DROP POLICY IF EXISTS communities_owner_insert ON public.communities;
DROP POLICY IF EXISTS communities_owner_update ON public.communities;
DROP POLICY IF EXISTS communities_owner_delete ON public.communities;
DROP POLICY IF EXISTS sellers_owner_all ON public.sellers;
DROP POLICY IF EXISTS products_owner_all ON public.products;
DROP POLICY IF EXISTS organizations_insert ON public.organizations;
DROP POLICY IF EXISTS organizations_update ON public.organizations;
DROP POLICY IF EXISTS org_members_select ON public.organization_members;
DROP POLICY IF EXISTS org_members_first_owner_insert ON public.organization_members;
DROP POLICY IF EXISTS org_members_admin_insert ON public.organization_members;
DROP POLICY IF EXISTS org_members_owner_update ON public.organization_members;
DROP POLICY IF EXISTS org_members_owner_delete ON public.organization_members;
DROP POLICY IF EXISTS org_permissions_select ON public.organization_permissions;
DROP POLICY IF EXISTS org_permissions_manage ON public.organization_permissions;
DROP POLICY IF EXISTS org_subscriptions_select ON public.organization_subscriptions;
DROP POLICY IF EXISTS org_payments_select ON public.organization_payments;
DROP POLICY IF EXISTS org_finances_all ON public.organization_finances;
DROP POLICY IF EXISTS org_documents_all ON public.organization_documents;
DROP POLICY IF EXISTS org_meetings_all ON public.organization_meetings;
DROP POLICY IF EXISTS org_letters_all ON public.organization_letters;
DROP POLICY IF EXISTS org_attendance_all ON public.organization_attendance;
DROP POLICY IF EXISTS org_tasks_all ON public.organization_tasks;
DROP POLICY IF EXISTS org_branches_all ON public.organization_branches;
DROP POLICY IF EXISTS publication_projects_all ON public.publication_projects;
DROP POLICY IF EXISTS publication_templates_manage ON public.publication_templates;
DROP POLICY IF EXISTS transcripts_all ON public.meeting_transcripts;
DROP POLICY IF EXISTS community_members_all ON public.community_members;
DROP POLICY IF EXISTS reports_insert ON public.reports;
DROP POLICY IF EXISTS reports_select ON public.reports;
DROP POLICY IF EXISTS reports_update ON public.reports;
DROP POLICY IF EXISTS events_manage ON public.events;
DROP POLICY IF EXISTS official_sources_editor_all ON public.official_sources;
DROP POLICY IF EXISTS official_offices_editor_all ON public.official_offices;
DROP POLICY IF EXISTS official_contacts_editor_all ON public.official_contacts;
DROP POLICY IF EXISTS official_evidence_editor_all ON public.official_evidence;
DROP POLICY IF EXISTS audit_super_select ON public.audit_logs;
DROP POLICY IF EXISTS audit_user_insert ON public.audit_logs;
DROP POLICY IF EXISTS sessions_system_all ON public.sessions;
DROP POLICY IF EXISTS memberships_system_all ON public.memberships;
DROP POLICY IF EXISTS payments_system_all ON public.payments;
DROP POLICY IF EXISTS org_subscriptions_system_all ON public.organization_subscriptions;
DROP POLICY IF EXISTS org_payments_system_all ON public.organization_payments;
DROP POLICY IF EXISTS notifications_system_all ON public.notifications;
DROP POLICY IF EXISTS official_sources_system_all ON public.official_sources;
DROP POLICY IF EXISTS official_offices_system_all ON public.official_offices;
DROP POLICY IF EXISTS official_contacts_system_all ON public.official_contacts;
DROP POLICY IF EXISTS official_evidence_system_all ON public.official_evidence;
DROP POLICY IF EXISTS audit_system_insert ON public.audit_logs;
DROP POLICY IF EXISTS system_reference_users ON public.users;
DROP POLICY IF EXISTS system_reference_orgs ON public.organizations;
DROP POLICY IF EXISTS system_reference_members ON public.organization_members;
DROP POLICY IF EXISTS members_self_select ON public.members;
DROP POLICY IF EXISTS members_admin_select ON public.members;
DROP POLICY IF EXISTS members_self_insert ON public.members;
DROP POLICY IF EXISTS members_self_update ON public.members;
DROP POLICY IF EXISTS members_admin_update ON public.members;
DROP POLICY IF EXISTS member_phone_challenges_self_all ON public.member_phone_challenges;
DROP POLICY IF EXISTS jobs_admin_all ON public.jobs;
DROP POLICY IF EXISTS communities_admin_all ON public.communities;
DROP POLICY IF EXISTS sellers_admin_all ON public.sellers;
DROP POLICY IF EXISTS products_admin_all ON public.products;
DROP POLICY IF EXISTS official_sources_admin_all ON public.official_sources;
DROP POLICY IF EXISTS organizations_admin_insert ON public.organizations;
DROP POLICY IF EXISTS organizations_admin_delete ON public.organizations;
DROP TRIGGER IF EXISTS protect_user_system_fields_trigger ON public.users;
DROP TRIGGER IF EXISTS protect_contents_moderation ON public.contents;
DROP TRIGGER IF EXISTS protect_communities_moderation ON public.communities;
DROP TRIGGER IF EXISTS protect_sellers_moderation ON public.sellers;
DROP TRIGGER IF EXISTS protect_products_moderation ON public.products;
DROP TRIGGER IF EXISTS protect_organizations_moderation ON public.organizations;
DROP TRIGGER IF EXISTS protect_publications_moderation ON public.publication_projects;
DROP TRIGGER IF EXISTS protect_member_workflow_trigger ON public.members;
DROP TRIGGER IF EXISTS protect_organization_workflow_trigger ON public.organizations;
DROP TRIGGER IF EXISTS protect_organization_archival_trigger ON public.organizations;
DROP FUNCTION IF EXISTS public.protect_user_system_fields();
DROP FUNCTION IF EXISTS public.protect_moderation_fields();
DROP FUNCTION IF EXISTS public.protect_member_workflow();
DROP FUNCTION IF EXISTS public.protect_organization_workflow();
DROP FUNCTION IF EXISTS public.protect_organization_archival();
DROP FUNCTION IF EXISTS public.current_app_has_org_role(uuid,public.organization_role[]);
DROP FUNCTION IF EXISTS public.current_app_has_role(public.user_role[]);
DROP FUNCTION IF EXISTS public.current_app_user_id();
DROP TABLE IF EXISTS public.member_phone_challenges;
DROP TABLE IF EXISTS public.members;
ALTER TABLE public.organizations DROP COLUMN IF EXISTS applicant_id;
ALTER TABLE public.organizations DROP COLUMN IF EXISTS registration_number;
ALTER TABLE public.organizations DROP COLUMN IF EXISTS category;
ALTER TABLE public.organizations DROP COLUMN IF EXISTS district;
ALTER TABLE public.organizations DROP COLUMN IF EXISTS address;
ALTER TABLE public.organizations DROP COLUMN IF EXISTS contact_person;
ALTER TABLE public.organizations DROP COLUMN IF EXISTS contact_phone;
ALTER TABLE public.organizations DROP COLUMN IF EXISTS contact_email;
ALTER TABLE public.organizations DROP COLUMN IF EXISTS application_status;
ALTER TABLE public.organizations DROP COLUMN IF EXISTS sk_document_url;
ALTER TABLE public.organizations DROP COLUMN IF EXISTS sk_document_uploaded_at;
ALTER TABLE public.organizations DROP COLUMN IF EXISTS sk_number;
ALTER TABLE public.organizations DROP COLUMN IF EXISTS sk_issue_date;
ALTER TABLE public.organizations DROP COLUMN IF EXISTS sk_expiry_date;
ALTER TABLE public.organizations DROP COLUMN IF EXISTS reviewed_by;
ALTER TABLE public.organizations DROP COLUMN IF EXISTS reviewed_at;
ALTER TABLE public.organizations DROP COLUMN IF EXISTS review_rejection_reason;
DROP TYPE IF EXISTS public.membership_status;
DROP TYPE IF EXISTS public.organization_application_status;
ALTER TABLE public.ai_conversations DISABLE ROW LEVEL SECURITY;
ALTER TABLE public.audit_logs DISABLE ROW LEVEL SECURITY;
ALTER TABLE public.communities DISABLE ROW LEVEL SECURITY;
ALTER TABLE public.community_members DISABLE ROW LEVEL SECURITY;
ALTER TABLE public.contents DISABLE ROW LEVEL SECURITY;
ALTER TABLE public.events DISABLE ROW LEVEL SECURITY;
ALTER TABLE public.jobs DISABLE ROW LEVEL SECURITY;
ALTER TABLE public.meeting_transcripts DISABLE ROW LEVEL SECURITY;
ALTER TABLE public.memberships DISABLE ROW LEVEL SECURITY;
ALTER TABLE public.notifications DISABLE ROW LEVEL SECURITY;
ALTER TABLE public.official_contacts DISABLE ROW LEVEL SECURITY;
ALTER TABLE public.official_evidence DISABLE ROW LEVEL SECURITY;
ALTER TABLE public.official_offices DISABLE ROW LEVEL SECURITY;
ALTER TABLE public.official_sources DISABLE ROW LEVEL SECURITY;
ALTER TABLE public.organization_attendance DISABLE ROW LEVEL SECURITY;
ALTER TABLE public.organization_branches DISABLE ROW LEVEL SECURITY;
ALTER TABLE public.organization_documents DISABLE ROW LEVEL SECURITY;
ALTER TABLE public.organization_finances DISABLE ROW LEVEL SECURITY;
ALTER TABLE public.organization_letters DISABLE ROW LEVEL SECURITY;
ALTER TABLE public.organization_meetings DISABLE ROW LEVEL SECURITY;
ALTER TABLE public.organization_members DISABLE ROW LEVEL SECURITY;
ALTER TABLE public.organization_payments DISABLE ROW LEVEL SECURITY;
ALTER TABLE public.organization_permissions DISABLE ROW LEVEL SECURITY;
ALTER TABLE public.organization_subscriptions DISABLE ROW LEVEL SECURITY;
ALTER TABLE public.organization_tasks DISABLE ROW LEVEL SECURITY;
ALTER TABLE public.organizations DISABLE ROW LEVEL SECURITY;
ALTER TABLE public.payments DISABLE ROW LEVEL SECURITY;
ALTER TABLE public.products DISABLE ROW LEVEL SECURITY;
ALTER TABLE public.publication_projects DISABLE ROW LEVEL SECURITY;
ALTER TABLE public.publication_templates DISABLE ROW LEVEL SECURITY;
ALTER TABLE public.reports DISABLE ROW LEVEL SECURITY;
ALTER TABLE public.sellers DISABLE ROW LEVEL SECURITY;
ALTER TABLE public.sessions DISABLE ROW LEVEL SECURITY;
ALTER TABLE public.users DISABLE ROW LEVEL SECURITY;
REVOKE ALL ON ALL TABLES IN SCHEMA public FROM duta_app,duta_system;
REVOKE ALL ON SCHEMA public FROM duta_app,duta_system;
REVOKE CONNECT ON DATABASE duta_rantau_staging FROM duta_app,duta_system;
DELETE FROM drizzle.__drizzle_migrations WHERE created_at IN (1787036103000,1787968300537,1787968301000,1788189382794,1788190000000,1788191000000);
COMMIT;
SELECT (SELECT count(*) FROM pg_tables WHERE schemaname='public' AND rowsecurity) rls_enabled,(SELECT count(*) FROM pg_policies WHERE schemaname='public') policy_count,(SELECT count(*) FROM drizzle.__drizzle_migrations) migration_count;
