import { afterEach, describe, expect, it, vi } from 'vitest';
import { AUTHORIZED_GROQ_MODEL, getConfiguredProvider } from '../lib/services/ai-provider-adapters';

const original = { geminiKey: process.env.GEMINI_API_KEY, geminiModel: process.env.GEMINI_MODEL, groqKey: process.env.GROQ_API_KEY, groqModel: process.env.GROQ_MODEL, openaiKey: process.env.OPENAI_API_KEY, openaiModel: process.env.OPENAI_MODEL };
afterEach(() => { Object.assign(process.env, { GEMINI_API_KEY: original.geminiKey, GEMINI_MODEL: original.geminiModel, GROQ_API_KEY: original.groqKey, GROQ_MODEL: original.groqModel, OPENAI_API_KEY: original.openaiKey, OPENAI_MODEL: original.openaiModel }); vi.unstubAllGlobals(); });
function configured(name: 'gemini'|'groq'|'openai') { process.env[`${name.toUpperCase()}_API_KEY`] = 'test-key'; if (name === 'gemini') process.env.GEMINI_MODEL = 'gemini-test'; if (name === 'groq') process.env.GROQ_MODEL = AUTHORIZED_GROQ_MODEL; if (name === 'openai') process.env.OPENAI_MODEL = 'gpt-5.6-luna'; }
function responseFor(name: string) { return new Response(JSON.stringify(name === 'gemini' ? { candidates: [{ content: { parts: [{ text: 'ok' }] } }] } : { choices: [{ message: { content: 'ok' } }] }), { status: 200, headers: { 'content-type': 'application/json' } }); }

describe('provider adapters', () => {
  it('fails closed without credentials and denies non-Luna OpenAI', async () => { delete process.env.OPENAI_API_KEY; expect(await getConfiguredProvider('openai').generate({ message: 'x', channel: 'text' })).toMatchObject({ success: false, errorCategory: 'UNAVAILABLE' }); process.env.OPENAI_API_KEY = 'test'; process.env.OPENAI_MODEL = 'terra'; expect(await getConfiguredProvider('openai').generate({ message: 'x', channel: 'text' })).toMatchObject({ success: false, errorCategory: 'UNAVAILABLE' }); });
  it.each(['gemini', 'groq', 'openai'] as const)('uses one minimized server-owned %s request with a 300-token ceiling', async name => {
    configured(name); const fetchMock = vi.fn(async (url: string, init: RequestInit) => { expect(init.method).toBe('POST'); expect(init.headers).toHaveProperty(name === 'gemini' ? 'Content-Type' : 'Authorization'); expect(init.signal).toBeInstanceOf(AbortSignal); const payload = JSON.parse(String(init.body)); expect(JSON.stringify(payload)).not.toContain('PRIVATE_PROVIDER_ERROR_MARKER_98765'); expect(name === 'gemini' ? payload.generationConfig.maxOutputTokens : payload.max_tokens).toBeLessThanOrEqual(300); if (name === 'openai') expect(payload.model).toBe('gpt-5.6-luna'); if (name === 'groq') expect(payload.model).toBe(AUTHORIZED_GROQ_MODEL); if (name === 'gemini') expect(url).toContain('generativelanguage.googleapis.com'); if (name === 'groq') expect(url).toContain('api.groq.com'); if (name === 'openai') expect(url).toContain('api.openai.com'); return responseFor(name); }); vi.stubGlobal('fetch', fetchMock);
    const result = await getConfiguredProvider(name).generate({ message: 'hello', channel: 'text', maxOutputTokens: 10_000 }); expect(result).toMatchObject({ success: true, provider: name, text: 'ok' }); expect(fetchMock).toHaveBeenCalledTimes(1);
  });
  it('locks Groq to its server allowlist and rejects arbitrary environment models before network use', async () => { process.env.GROQ_API_KEY = 'test'; delete process.env.GROQ_MODEL; const fetchMock = vi.fn(async () => responseFor('groq')); vi.stubGlobal('fetch', fetchMock); await expect(getConfiguredProvider('groq').generate({ message: 'hello', channel: 'text' })).resolves.toMatchObject({ success: true, model: AUTHORIZED_GROQ_MODEL }); expect(fetchMock).toHaveBeenCalledTimes(1); process.env.GROQ_MODEL = 'openai/gpt-oss-120b'; fetchMock.mockClear(); await expect(getConfiguredProvider('groq').generate({ message: 'hello', channel: 'text' })).resolves.toMatchObject({ success: false, errorCategory: 'UNAVAILABLE' }); expect(fetchMock).not.toHaveBeenCalled(); });
  it.each(['gemini', 'groq', 'openai'] as const)('normalizes %s raw failures without retry or error-body leakage', async name => { configured(name); const marker = 'PRIVATE_PROVIDER_ERROR_MARKER_98765'; const fetchMock = vi.fn(async () => new Response(marker, { status: 500 })); vi.stubGlobal('fetch', fetchMock); const result = await getConfiguredProvider(name).generate({ message: 'hello', channel: 'text' }); expect(result).toMatchObject({ success: false, errorCategory: 'UNAVAILABLE' }); expect(JSON.stringify(result)).not.toContain(marker); expect(fetchMock).toHaveBeenCalledTimes(1); });
});