import { describe, expect, it, vi } from 'vitest';
import { renderToStaticMarkup } from 'react-dom/server';
const story = { publicSlug: 'maklumat-rasmi', displayTitle: 'Maklumat rasmi', conciseSummary: 'Ringkasan yang jelas.', contentType: 'ANNOUNCEMENT', publishedAt: '2026-09-30T00:00:00.000Z', updatedAt: '2026-09-30T00:00:00.000Z', sourcePublishedAt: '2026-09-29T00:00:00.000Z', canonicalUrl: 'https://instagram.com/p/official', originalUrl: 'https://instagram.com/p/official', originalSourcePublishedAt: '2026-09-29T00:00:00.000Z', officialSourceInstitution: 'KBRI Kuala Lumpur', officialSourceChannel: 'INSTAGRAM', sourceReferences: [{ institution: 'KBRI Kuala Lumpur', channel: 'INSTAGRAM', originalUrl: 'https://instagram.com/p/official', sourcePublishedAt: '2026-09-29T00:00:00.000Z' }, { institution: 'KJRI Penang', channel: 'FACEBOOK', originalUrl: 'https://facebook.com/official', sourcePublishedAt: null }] };
const mocked = vi.hoisted(() => ({ page: vi.fn(), story: vi.fn() }));
vi.mock('@/lib/services/public-news', () => ({ getPublicNewsPage: mocked.page, getPublicNewsBySlug: mocked.story }));
const InfoPage = (await import('../app/info/page')).default;
const StoryPage = (await import('../app/info/[slug]/page')).default;
describe('public Info Rantau rendering', () => {
  it('renders a populated SSR list with a DUTA summary and public story link', async () => { mocked.page.mockResolvedValue({ stories: [story], page: 1, pageSize: 20, hasMore: false }); const html = renderToStaticMarkup(await InfoPage({ searchParams: Promise.resolve({}) })); expect(html).toContain('Ringkasan oleh DUTA'); expect(html).toContain('/info/maklumat-rasmi'); expect(html).toContain('KBRI Kuala Lumpur'); });
  it('renders the empty state only after a successful empty result', async () => { mocked.page.mockResolvedValue({ stories: [], page: 1, pageSize: 20, hasMore: false }); const html = renderToStaticMarkup(await InfoPage({ searchParams: Promise.resolve({}) })); expect(html).toContain('Belum ada artikel terverifikasi untuk diterbitkan.'); });
  it('renders title, source permalink, attribution and breadcrumbs for a story', async () => { mocked.story.mockResolvedValue(story); const html = renderToStaticMarkup(await StoryPage({ params: Promise.resolve({ slug: story.publicSlug }) })); expect(html).toContain('<h1>Maklumat rasmi</h1>'); expect(html).toContain('Ringkasan oleh DUTA'); expect(html).toContain('Baca informasi asli — KBRI Kuala Lumpur/Instagram'); expect(html).toContain('https://instagram.com/p/official'); expect(html).toContain('Info Rantau'); });
  it('does not turn unknown or unavailable stories into a successful page', async () => { mocked.story.mockResolvedValue(null); await expect(StoryPage({ params: Promise.resolve({ slug: 'withdrawn-story' }) })).rejects.toMatchObject({ digest: expect.stringContaining('NEXT_HTTP_ERROR_FALLBACK;404') }); });
  it('allows a database error to escape instead of presenting an empty list', async () => { mocked.page.mockRejectedValue(new Error('database unavailable')); await expect(InfoPage({ searchParams: Promise.resolve({}) })).rejects.toThrow('database unavailable'); });
});
