'use client';

import { useEffect, useState } from 'react';

type Kind = 'jobs' | 'marketplace' | 'community' | 'organizations';
const endpoint: Record<Kind, string> = { jobs: '/api/admin/jobs', marketplace: '/api/admin/marketplace', community: '/api/admin/community', organizations: '/api/admin/organizations' };
const idField: Record<Kind, string> = { jobs: 'jobId', marketplace: 'productId', community: 'communityId', organizations: 'organizationId' };

export function AdminContentManager() {
  const [data, setData] = useState<Record<Kind, Array<Record<string, unknown>>>>({ jobs: [], marketplace: [], community: [], organizations: [] });
  const [message, setMessage] = useState(''); const [error, setError] = useState(''); const [busy, setBusy] = useState('');
  async function load() { const responses = await Promise.all((Object.keys(endpoint) as Kind[]).map(async (kind) => { const response = await fetch(endpoint[kind]); const body = await response.json().catch(() => ({})); if (!response.ok) throw new Error(body.error ?? `Data ${kind} belum tersedia.`); return [kind, body.data ?? []] as const; })); setData(Object.fromEntries(responses) as Record<Kind, Array<Record<string, unknown>>>); }
  useEffect(() => { load().catch((cause) => setError(cause instanceof Error ? cause.message : 'Data konten belum tersedia.')); }, []);
  async function mutate(kind: Kind, method: 'POST' | 'PATCH' | 'DELETE', payload: Record<string, unknown>) { setBusy(`${method}:${kind}`); setError(''); setMessage(''); try { const response = await fetch(endpoint[kind], { method, headers: { 'content-type': 'application/json' }, body: JSON.stringify(payload) }); const body = await response.json().catch(() => ({})); if (!response.ok) throw new Error(body.error ?? 'Operasi konten gagal.'); setMessage('Perubahan disimpan.'); await load(); } catch (cause) { setError(cause instanceof Error ? cause.message : 'Operasi konten gagal.'); } finally { setBusy(''); } }
  async function create(kind: Kind, event: React.FormEvent<HTMLFormElement>) { event.preventDefault(); const values = Object.fromEntries(new FormData(event.currentTarget)); const payload = kind === 'jobs' ? { ...values, employmentType: values.employmentType || 'INFORMATION', recordStatus: 'PENDING' } : kind === 'marketplace' ? { ...values, category: values.category || 'Umum', recordStatus: 'PENDING' } : kind === 'community' ? { ...values, category: values.category || 'Umum', visibility: 'PUBLIC', recordStatus: 'PENDING' } : { ...values, type: values.type || 'Organisasi', recordStatus: 'PENDING' }; await mutate(kind, 'POST', payload); event.currentTarget.reset(); }
  return <div className="admin-content-manager">{message && <div className="success-box" role="status">{message}</div>}{error && <div className="error-box" role="alert">{error}</div>}<div className="content-admin-grid">{(Object.keys(endpoint) as Kind[]).map((kind) => <section className="review-panel" key={kind}><div className="section-title"><h2>{kind === 'jobs' ? 'Jobs' : kind === 'marketplace' ? 'Marketplace' : kind === 'community' ? 'Community' : 'Organizations'}</h2><span>{data[kind].length} record database</span></div><form className="admin-quick-create" onSubmit={(event) => create(kind, event)}><input name={kind === 'jobs' ? 'title' : 'name'} required placeholder={kind === 'jobs' ? 'Judul' : 'Nama'} /><input name={kind === 'jobs' ? 'employer' : kind === 'marketplace' ? 'sellerName' : kind === 'organizations' ? 'type' : 'category'} required placeholder={kind === 'jobs' ? 'Employer' : kind === 'marketplace' ? 'Penjual' : kind === 'organizations' ? 'Tipe' : 'Kategori'} /><textarea name="description" required minLength={10} placeholder="Deskripsi" rows={2} /><button className="primary" disabled={busy === `POST:${kind}`}>{busy === `POST:${kind}` ? 'Membuat…' : 'Buat record'}</button></form><div className="content-admin-list">{data[kind].length === 0 ? <p className="review-empty">Belum ada data.</p> : data[kind].slice(0, 20).map((item) => { const id = String(item.id); const status = String(item.recordStatus ?? item.applicationStatus ?? 'PENDING'); return <article key={id}><div><b>{String(item.name ?? item.title ?? 'Tanpa nama')}</b><small>{status}</small></div><div className="review-actions"><button className="secondary-button" onClick={() => mutate(kind, 'PATCH', { [idField[kind]]: id, recordStatus: status === 'ACTIVE' ? 'ARCHIVED' : 'ACTIVE' })}>{status === 'ACTIVE' ? 'Archive' : 'Publish'}</button><button className="secondary-button danger-button" onClick={() => mutate(kind, 'DELETE', { [idField[kind]]: id })}>{kind === 'organizations' ? 'Archive' : 'Delete'}</button></div></article>; })}</div></section>)}</div></div>;
}
