'use client';
import { useEffect,useMemo,useState } from 'react';
import { AlertTriangle,CheckCircle2,ExternalLink,LocateFixed,MapPin,MessageCircle,Phone,ShieldCheck } from 'lucide-react';
import { officialEmergencyOffices,type OfficialOfficeContact } from '@/lib/official-emergency-data';
const places=[['Kuala Lumpur',3.139,101.687],['Selangor',3.0738,101.5183],['Johor',1.4927,103.7414],['Pulau Pinang',5.4141,100.3288],['Kedah',6.1184,100.3685],['Perak',4.5975,101.0901],['Perlis',6.4414,100.1986],['Kelantan',6.1254,102.2381],['Terengganu',5.3117,103.1324],['Pahang',3.8077,103.326],['Melaka',2.1896,102.2501],['Negeri Sembilan',2.7258,101.9424],['Sarawak',1.5533,110.3592],['Sabah — Kota Kinabalu dan sekitar',5.9804,116.0735],['Sabah Timur — Tawau dan sekitar',4.2448,117.8912]] as const;
const rad=(x:number)=>x*Math.PI/180;
function distance(a:{lat:number;lng:number},b:{lat:number;lng:number}){const dLat=rad(b.lat-a.lat),dLng=rad(b.lng-a.lng);const h=Math.sin(dLat/2)**2+Math.cos(rad(a.lat))*Math.cos(rad(b.lat))*Math.sin(dLng/2)**2;return 6371*2*Math.atan2(Math.sqrt(h),Math.sqrt(1-h))}
function message(office:OfficialOfficeContact,locationLabel:string,coords?:{lat:number;lng:number}){const location=coords?`${locationLabel} (${coords.lat.toFixed(5)}, ${coords.lng.toFixed(5)})`:locationLabel;return encodeURIComponent(`Saya WNI membutuhkan bantuan segera. Lokasi saya: ${location}. Mohon arahan dari ${office.institution}.`)}
export function EmergencyContacts(){
 const [place,setPlace]=useState('Kuala Lumpur');
 const [coords,setCoords]=useState<{lat:number;lng:number}|null>({lat:3.139,lng:101.687});
 const [geoStatus,setGeoStatus]=useState('');
 const [offices,setOffices]=useState<OfficialOfficeContact[]>(officialEmergencyOffices);
 const [directoryStatus,setDirectoryStatus]=useState<'loading'|'live'|'fallback'>('loading');
 useEffect(()=>{let active=true;fetch('/api/safety/contacts').then(r=>r.json()).then(result=>{if(!active||!Array.isArray(result.data)||!result.data.length)return;setOffices(result.data);setDirectoryStatus(result.meta?.fallback?'fallback':'live')}).catch(()=>active&&setDirectoryStatus('fallback'));return()=>{active=false}},[]);
 const nearest=useMemo(()=>!coords?offices:[...offices].sort((a,b)=>distance(coords,a)-distance(coords,b)),[coords,offices]);
 function choose(value:string){setPlace(value);const p=places.find(x=>x[0]===value);if(p)setCoords({lat:p[1],lng:p[2]})}
 function locate(){if(!navigator.geolocation){setGeoStatus('Lokasi perangkat tidak tersedia.');return}setGeoStatus('Mencari lokasi…');navigator.geolocation.getCurrentPosition(p=>{setCoords({lat:p.coords.latitude,lng:p.coords.longitude});setPlace('Lokasi perangkat');setGeoStatus('Lokasi dipakai sementara di perangkat ini dan tidak disimpan.')},()=>setGeoStatus('Izin lokasi tidak diberikan. Pilih lokasi secara manual.'),{enableHighAccuracy:false,timeout:8000,maximumAge:300000})}
 if(!nearest.length)return <div className="error-box">Direktori kontak belum tersedia. Buka kanal resmi perwakilan RI.</div>;
 return <section className="emergency-directory"><div className="directory-head"><div><span className="eyebrow">KONTAK BERDASARKAN LOKASI</span><h2>Perwakilan RI terdekat</h2><p>Urutan dihitung secara geografis, bukan penetapan yurisdiksi resmi.</p><span className={`directory-status ${directoryStatus}`}>{directoryStatus==='live'?'● Data langsung Supabase':directoryStatus==='fallback'?'● Data terverifikasi tersimpan':'● Memeriksa data langsung…'}</span></div><div className="location-controls"><label><MapPin/><select value={place} onChange={e=>choose(e.target.value)}>{place==='Lokasi perangkat'&&<option>Lokasi perangkat</option>}{places.map(p=><option key={p[0]}>{p[0]}</option>)}</select></label><button onClick={locate}><LocateFixed/>Gunakan lokasi saya</button></div></div>{geoStatus&&<p className="geo-status"><ShieldCheck/>{geoStatus}</p>}<div className="nearest-highlight"><LocateFixed/><span>Paling dekat secara geografis</span><b>{nearest[0].institution} · {nearest[0].city}</b>{coords&&<small>± {Math.round(distance(coords,nearest[0]))} km</small>}</div><div className="emergency-office-list">{nearest.map((office,index)=><article key={office.id} className={index===0?'nearest':''}><header><div><span>{index===0?'TERDEKAT':'PERWAKILAN RI'}</span><h3>{office.institution}</h3><p><MapPin/>{office.city} · {office.region}</p></div><a href={office.officialUrl} target="_blank" rel="noreferrer">Sumber resmi <ExternalLink/></a></header>{office.contacts.length===0?<div className="no-number"><AlertTriangle/><p><b>Nomor pengaduan belum tersedia dalam bukti terlampir.</b>DUTA tidak menebak nomor. Gunakan kanal resmi institusi.</p></div>:<div className="contact-list">{office.contacts.map(contact=><div key={contact.id}><div><b>{contact.label}</b><a href={`tel:+${contact.e164}`}><Phone/>{contact.number}</a><small>{contact.purpose}</small>{contact.warning&&<em>{contact.warning}</em>}</div><div className="contact-actions"><a className="call-action" href={`tel:+${contact.e164}`}><Phone/>Telepon</a>{contact.channel!=='PHONE'&&contact.channel!=='APPOINTMENT_ONLY'&&<a className="wa-action" href={`https://wa.me/${contact.e164}?text=${message(office,place,coords??undefined)}`} target="_blank" rel="noreferrer"><MessageCircle/>{contact.channel==='WHATSAPP_CONFIRMED'?'WhatsApp':'Coba WhatsApp'}</a>}</div></div>)}</div>}<footer><CheckCircle2/><span>Sumber: {office.sourceChannel}</span><b>Diperiksa {new Date(office.lastChecked+'T00:00:00').toLocaleDateString('id-ID',{day:'numeric',month:'short',year:'numeric'})}</b></footer></article>)}</div><div className="contact-disclaimer"><AlertTriangle/><p><b>DUTA RANTAU bukan layanan darurat atau institusi pemerintah.</b>Nomor dapat berubah. Periksa kembali kanal resmi. Jangan menunggu balasan WhatsApp jika keselamatan terancam; gunakan opsi telepon dan cari bantuan darurat setempat.</p></div></section>
}
