'use client';
import Link from 'next/link';
import { useEffect, useState } from 'react';
import { ArrowUpRight } from 'lucide-react';

function Row({href,title,text}:{href:string;title:string;text:string}){return <Link className="vp-row" href={href}><span><strong>{title}</strong><small>{text}</small></span><ArrowUpRight size={20}/></Link>}

function MemberHariIni(){return <div className="vp-member-shell"><style jsx global>{`.vp-hari-public{display:none}`}</style><div className="vp-page vp-wide"><header className="vp-top"><span className="vp-eyebrow">Hari Ini · Member</span><h1>Untuk Anda,<br/><em>masih berjalan.</em></h1><p className="vp-lead">Ruang ini hanya menampilkan hal yang benar-benar tersedia untuk akun Anda.</p></header><div className="vp-grid"><div><section className="vp-member-thread"><span className="vp-kicker">Lanjutkan dari DUTA Anda</span><h2>Satu langkah kecil menjaga semuanya dekat.</h2><div className="vp-empty"><strong>Belum ada kelanjutan tersimpan.</strong><p>Simpanan, rencana, dan hubungan yang nyata akan muncul di sini bila tersedia.</p><Link className="vp-quiet" href="/tanya">Mulai dengan Tanya DUTA <ArrowUpRight size={16}/></Link></div></section><section className="vp-section"><h2>Untuk Anda</h2><Row href="/belajar" title="Bekal anti-scam" text="Panduan yang tersedia, tanpa kemajuan rekaan"/><Row href="/kerja" title="Jalur kerja" text="Periksa sumber sebelum bertindak"/></section></div><div><figure className="vp-scene"><img src="/visual-r21f/hari-commute.webp" alt="Ilustrasi AI perjalanan sehari-hari di Malaysia"/><figcaption>Momen Hari Ini · prototipe AI</figcaption></figure><p>Momen ilustratif, bukan data atau aktivitas Member sebenarnya.</p><section className="vp-section"><h2>Penting Hari Ini</h2><Row href="/layanan" title="Kenali kanal perwakilan Anda" text="Periksa sumber resmi sebelum melangkah"/><h2>Sekitar Anda</h2><div className="vp-empty"><strong>Area belum dipilih.</strong><p>Tidak ada hasil sekitar atau lokasi yang ditebak.</p></div><h2>Update Resmi</h2><Row href="/info" title="Buka sumber dan panduan" text="Belum ada pembaruan akun yang diverifikasi"/></section></div></div><footer className="vp-footer"><span>DUTA tidak mengarang kelanjutan akun.</span><Link href="/profil">Lihat Saya <ArrowUpRight size={16}/></Link></footer></div></div>}

export function HariIniMember(){const [isMember,setIsMember]=useState(false);useEffect(()=>{let active=true;fetch('/api/auth/me',{credentials:'same-origin'}).then(r=>r.ok?r.json():null).then(payload=>{if(active)setIsMember(Boolean(payload?.user))}).catch(()=>{if(active)setIsMember(false)});return()=>{active=false}},[]);return isMember?<MemberHariIni/>:null}
