import Link from 'next/link';
import { ArrowUpRight } from 'lucide-react';
import { communities } from '@/db/schema';
import { withPublicTransaction } from '@/lib/db/identity-bridge';
export const dynamic='force-dynamic';
export const metadata={title:'Kawan Rantau'};
async function getCommunities(){return withPublicTransaction(async tx=>tx.select().from(communities))}
function Row({href,title,text}:{href:string;title:string;text:string}){return <Link className="vp-row" href={href}><span><strong>{title}</strong><small>{text}</small></span><ArrowUpRight size={20}/></Link>}
export default async function Page(){const records=await getCommunities().catch(()=>[]);return <div className="vp-page vp-wide"><header className="vp-top"><span className="vp-eyebrow">Rantau</span><h1>Rasa dekat,<br/><em>meski di rantau.</em></h1><p className="vp-lead">Mulai dari minat yang sama. Temukan ruang untuk berkenalan dan berkegiatan.</p></header><figure className="vp-scene vp-rantau-scene"><img src="/visual-r21f/rantau-community.webp" alt="Ilustrasi AI sekelompok perantau berbincang di Malaysia; bukan anggota nyata"/><figcaption>Momen Komuniti · prototipe AI</figcaption></figure><p>Ilustrasi karakter DUTA; bukan anggota atau testimoni komunitas.</p><section className="vp-section"><h2>Kawan Rantau</h2><nav className="vp-tabs" aria-label="Ruang Rantau"><a href="#orang">Orang</a><a href="#komuniti" aria-current="page">Komuniti</a><a href="#aktiviti">Aktiviti</a></nav><span className="vp-note">Konten dan tindakan mengikuti batas beta yang nyata.</span></section><section id="orang" className="vp-section"><h2>Saling mengenal, dengan konteks.</h2><div className="vp-empty"><strong>Penemuan orang belum tersedia.</strong><p>Profil publik dan hubungan antaranggota belum ditampilkan.</p></div></section><section id="komuniti" className="vp-section"><h2>Komuniti</h2><p>Ruang yang tersedia dapat ditemukan. Pembuatan, Join, Leave, dan chat belum dibuka pada beta ini.</p>{records.length?records.map((record:Awaited<ReturnType<typeof getCommunities>>[number])=><div className="vp-row" key={record.id}><span><strong>{record.name}</strong><small>{record.location||'Lokasi tidak ditampilkan'} · {record.visibility==='COMMUNITY_ONLY'?'Akses terbatas':'Discovery publik'}</small></span><Link href="/tanya">Tanya konteks <ArrowUpRight size={16}/></Link></div>):<div className="vp-empty"><strong>Belum ada komuniti yang dapat ditampilkan.</strong><p>DUTA tidak membuat keanggotaan atau komunitas contoh.</p></div>}</section><section id="aktiviti" className="vp-section"><h2>Aktiviti</h2><div className="vp-empty"><strong>Belum ada aktivitas yang dapat ditampilkan.</strong><p>Jadwal, RSVP, dan jumlah peserta tidak direka.</p></div></section><section className="vp-section"><Row href="/organisasi" title="Organisasi" text="Kenali entitas, kegiatan, dan perwakilannya"/></section><footer className="vp-footer"><Link href="/beranda">Kembali ke Hari Ini <ArrowUpRight size={16}/></Link></footer></div>}
