import { pgTable, uuid, text, timestamp, boolean, integer, numeric, jsonb, pgEnum, uniqueIndex, index } from 'drizzle-orm/pg-core';

export const userRole = pgEnum('user_role', ['USER','MEMBER','VERIFIED_MEMBER','SELLER','ORG_ADMIN','ORG_STAFF','MODERATOR','EDITOR','SUPER_ADMIN']);
export const status = pgEnum('record_status', ['DRAFT','PENDING','ACTIVE','SUSPENDED','ARCHIVED']);
export const trust = pgEnum('trust_level', ['OFFICIAL_VERIFIED','INSTITUTION_VERIFIED','DUTA_VERIFIED','COMMUNITY_VERIFIED','USER_GENERATED']);
export const orgRole = pgEnum('organization_role', ['OWNER','ADMIN','SECRETARY','TREASURER','STAFF','MEMBER']);

const audit = {
  createdAt: timestamp('created_at', { withTimezone:true }).defaultNow().notNull(),
  updatedAt: timestamp('updated_at', { withTimezone:true }).defaultNow().notNull(),
};
export const users = pgTable('users', {
  id: uuid('id').defaultRandom().primaryKey(), email:text('email').notNull(), passwordHash:text('password_hash'),
  name:text('name').notNull(), phone:text('phone'), avatarUrl:text('avatar_url'), city:text('city'), state:text('state'),
  hometown:text('hometown'), profession:text('profession'), interests:text('interests').array(), role:userRole('role').default('USER').notNull(),
  emailVerifiedAt:timestamp('email_verified_at',{withTimezone:true}), profileVisibility:text('profile_visibility').default('PRIVATE').notNull(),
  locationVisibility:text('location_visibility').default('PRIVATE').notNull(), suspendedAt:timestamp('suspended_at',{withTimezone:true}), ...audit,
}, t=>[uniqueIndex('users_email_uq').on(t.email), index('users_location_idx').on(t.state,t.city)]);
export const sessions = pgTable('sessions', { id:uuid('id').defaultRandom().primaryKey(), userId:uuid('user_id').references(()=>users.id,{onDelete:'cascade'}).notNull(), tokenHash:text('token_hash').notNull(), expiresAt:timestamp('expires_at',{withTimezone:true}).notNull(), createdAt:timestamp('created_at',{withTimezone:true}).defaultNow().notNull() },t=>[uniqueIndex('session_token_uq').on(t.tokenHash),index('session_user_idx').on(t.userId)]);
export const memberships = pgTable('memberships',{ id:uuid('id').defaultRandom().primaryKey(),userId:uuid('user_id').references(()=>users.id,{onDelete:'cascade'}).notNull(),plan:text('plan').notNull(),status:text('status').notNull(),priceMyr:numeric('price_myr',{precision:10,scale:2}),startDate:timestamp('start_date',{withTimezone:true}),renewalDate:timestamp('renewal_date',{withTimezone:true}),cancelledAt:timestamp('cancelled_at',{withTimezone:true}),eastelBonusStatus:text('eastel_bonus_status').default('NOT_CLAIMED'),...audit});
export const organizations = pgTable('organizations',{id:uuid('id').defaultRandom().primaryKey(),name:text('name').notNull(),type:text('type').notNull(),description:text('description'),state:text('state'),city:text('city'),logoUrl:text('logo_url'),contact:text('contact'),verification:trust('verification').default('USER_GENERATED').notNull(),recordStatus:status('status').default('PENDING').notNull(),...audit});
export const organizationMembers = pgTable('organization_members',{organizationId:uuid('organization_id').references(()=>organizations.id,{onDelete:'cascade'}).notNull(),userId:uuid('user_id').references(()=>users.id,{onDelete:'cascade'}).notNull(),role:orgRole('role').default('MEMBER').notNull(),memberStatus:text('member_status').default('ACTIVE').notNull(),joinedAt:timestamp('joined_at',{withTimezone:true}).defaultNow().notNull()},t=>[uniqueIndex('org_member_uq').on(t.organizationId,t.userId)]);
export const orgPermissions = pgTable('organization_permissions',{id:uuid('id').defaultRandom().primaryKey(),organizationId:uuid('organization_id').references(()=>organizations.id,{onDelete:'cascade'}).notNull(),role:orgRole('role').notNull(),permission:text('permission').notNull()},t=>[uniqueIndex('org_permission_uq').on(t.organizationId,t.role,t.permission)]);
export const officialSources = pgTable('official_sources',{id:uuid('id').defaultRandom().primaryKey(),institution:text('institution').notNull(),channel:text('channel').notNull(),url:text('url').notNull(),category:text('category').notNull(),priority:text('priority').notNull(),trustLevel:trust('trust_level').default('OFFICIAL_VERIFIED').notNull(),lastChecked:timestamp('last_checked',{withTimezone:true}).notNull(),checksum:text('checksum'),active:boolean('active').default(true).notNull(),...audit},t=>[uniqueIndex('sources_url_uq').on(t.url),index('source_institution_idx').on(t.institution)]);
export const contents = pgTable('contents',{id:uuid('id').defaultRandom().primaryKey(),authorId:uuid('author_id').references(()=>users.id),title:text('title').notNull(),slug:text('slug').notNull(),body:text('body').notNull(),type:text('type').notNull(),category:text('category'),state:text('state'),city:text('city'),trustLevel:trust('trust_level').default('USER_GENERATED').notNull(),sourceId:uuid('source_id').references(()=>officialSources.id),recordStatus:status('status').default('DRAFT').notNull(),publishedAt:timestamp('published_at',{withTimezone:true}),...audit},t=>[uniqueIndex('content_slug_uq').on(t.slug)]);
export const jobs = pgTable('jobs',{id:uuid('id').defaultRandom().primaryKey(),ownerId:uuid('owner_id').references(()=>users.id),title:text('title').notNull(),employer:text('employer').notNull(),description:text('description').notNull(),state:text('state'),city:text('city'),salaryText:text('salary_text'),employmentType:text('employment_type').notNull(),requirements:text('requirements'),language:text('language'),applicationMethod:text('application_method'),trustLevel:trust('trust_level').default('USER_GENERATED').notNull(),expiresAt:timestamp('expires_at',{withTimezone:true}),recordStatus:status('status').default('PENDING').notNull(),...audit},t=>[index('jobs_search_idx').on(t.state,t.city,t.employmentType)]);
export const sellers = pgTable('sellers',{id:uuid('id').defaultRandom().primaryKey(),userId:uuid('user_id').references(()=>users.id),organizationId:uuid('organization_id').references(()=>organizations.id),name:text('name').notNull(),description:text('description'),trustLevel:trust('trust_level').default('USER_GENERATED').notNull(),recordStatus:status('status').default('PENDING').notNull(),...audit});
export const products = pgTable('products',{id:uuid('id').defaultRandom().primaryKey(),sellerId:uuid('seller_id').references(()=>sellers.id,{onDelete:'cascade'}).notNull(),name:text('name').notNull(),description:text('description').notNull(),category:text('category').notNull(),priceMyr:numeric('price_myr',{precision:12,scale:2}),images:jsonb('images').$type<string[]>().default([]),state:text('state'),city:text('city'),recordStatus:status('status').default('PENDING').notNull(),...audit});
export const events = pgTable('events',{id:uuid('id').defaultRandom().primaryKey(),organizationId:uuid('organization_id').references(()=>organizations.id,{onDelete:'cascade'}),title:text('title').notNull(),description:text('description'),location:text('location'),startsAt:timestamp('starts_at',{withTimezone:true}).notNull(),capacity:integer('capacity'),registrationEnabled:boolean('registration_enabled').default(true),recordStatus:status('status').default('DRAFT').notNull(),...audit});
export const orgFinances = pgTable('organization_finances',{id:uuid('id').defaultRandom().primaryKey(),organizationId:uuid('organization_id').references(()=>organizations.id,{onDelete:'cascade'}).notNull(),actorId:uuid('actor_id').references(()=>users.id).notNull(),type:text('type').notNull(),amount:numeric('amount',{precision:14,scale:2}).notNull(),description:text('description').notNull(),transactionAt:timestamp('transaction_at',{withTimezone:true}).notNull(),...audit},t=>[index('finance_org_idx').on(t.organizationId,t.transactionAt)]);
export const communities = pgTable('communities',{id:uuid('id').defaultRandom().primaryKey(),ownerId:uuid('owner_id').references(()=>users.id),name:text('name').notNull(),description:text('description'),category:text('category').notNull(),state:text('state'),city:text('city'),visibility:text('visibility').default('PUBLIC').notNull(),trustLevel:trust('trust_level').default('USER_GENERATED').notNull(),recordStatus:status('status').default('PENDING').notNull(),...audit},t=>[index('community_location_idx').on(t.state,t.city,t.category)]);
export const communityMembers = pgTable('community_members',{communityId:uuid('community_id').references(()=>communities.id,{onDelete:'cascade'}).notNull(),userId:uuid('user_id').references(()=>users.id,{onDelete:'cascade'}).notNull(),role:text('role').default('MEMBER').notNull(),joinedAt:timestamp('joined_at',{withTimezone:true}).defaultNow().notNull()},t=>[uniqueIndex('community_member_uq').on(t.communityId,t.userId)]);
export const organizationDocuments = pgTable('organization_documents',{id:uuid('id').defaultRandom().primaryKey(),organizationId:uuid('organization_id').references(()=>organizations.id,{onDelete:'cascade'}).notNull(),authorId:uuid('author_id').references(()=>users.id).notNull(),type:text('type').notNull(),title:text('title').notNull(),storageKey:text('storage_key'),content:text('content'),recordStatus:status('status').default('DRAFT').notNull(),...audit},t=>[index('org_document_idx').on(t.organizationId,t.type)]);
export const organizationMeetings = pgTable('organization_meetings',{id:uuid('id').defaultRandom().primaryKey(),organizationId:uuid('organization_id').references(()=>organizations.id,{onDelete:'cascade'}).notNull(),title:text('title').notNull(),agenda:text('agenda'),minutes:text('minutes'),startsAt:timestamp('starts_at',{withTimezone:true}).notNull(),location:text('location'),recordStatus:status('status').default('DRAFT').notNull(),...audit});
export const organizationLetters = pgTable('organization_letters',{id:uuid('id').defaultRandom().primaryKey(),organizationId:uuid('organization_id').references(()=>organizations.id,{onDelete:'cascade'}).notNull(),number:text('number'),direction:text('direction').notNull(),title:text('title').notNull(),content:text('content'),approvalStatus:text('approval_status').default('DRAFT').notNull(),approvedBy:uuid('approved_by').references(()=>users.id),...audit},t=>[index('org_letter_idx').on(t.organizationId,t.direction)]);
export const payments = pgTable('payments',{id:uuid('id').defaultRandom().primaryKey(),membershipId:uuid('membership_id').references(()=>memberships.id,{onDelete:'cascade'}).notNull(),provider:text('provider').notNull(),providerReference:text('provider_reference'),amountMyr:numeric('amount_myr',{precision:10,scale:2}).notNull(),status:text('status').notNull(),invoiceNumber:text('invoice_number'),failureCode:text('failure_code'),paidAt:timestamp('paid_at',{withTimezone:true}),...audit},t=>[uniqueIndex('payment_provider_ref_uq').on(t.provider,t.providerReference)]);
export const notifications = pgTable('notifications',{id:uuid('id').defaultRandom().primaryKey(),userId:uuid('user_id').references(()=>users.id,{onDelete:'cascade'}).notNull(),type:text('type').notNull(),priority:text('priority').notNull(),title:text('title').notNull(),body:text('body').notNull(),readAt:timestamp('read_at',{withTimezone:true}),createdAt:timestamp('created_at',{withTimezone:true}).defaultNow().notNull()},t=>[index('notification_user_idx').on(t.userId,t.readAt)]);
export const aiConversations = pgTable('ai_conversations',{id:uuid('id').defaultRandom().primaryKey(),userId:uuid('user_id').references(()=>users.id,{onDelete:'set null'}),intent:text('intent'),messages:jsonb('messages').notNull(),sourceIds:uuid('source_ids').array(),confidence:text('confidence'),createdAt:timestamp('created_at',{withTimezone:true}).defaultNow().notNull()});
export const reports = pgTable('reports',{id:uuid('id').defaultRandom().primaryKey(),reporterId:uuid('reporter_id').references(()=>users.id),entityType:text('entity_type').notNull(),entityId:uuid('entity_id').notNull(),category:text('category').notNull(),details:text('details'),status:text('status').default('OPEN').notNull(),...audit});
export const auditLogs = pgTable('audit_logs',{id:uuid('id').defaultRandom().primaryKey(),actorId:uuid('actor_id').references(()=>users.id),organizationId:uuid('organization_id').references(()=>organizations.id),action:text('action').notNull(),entityType:text('entity_type').notNull(),entityId:text('entity_id'),metadata:jsonb('metadata'),ipHash:text('ip_hash'),createdAt:timestamp('created_at',{withTimezone:true}).defaultNow().notNull()},t=>[index('audit_actor_idx').on(t.actorId,t.createdAt)]);
