import { pgTable, uuid, text, timestamp, boolean, integer, numeric, jsonb, pgEnum, uniqueIndex, index } from 'drizzle-orm/pg-core';
import { sql } from 'drizzle-orm';

export const userRole = pgEnum('user_role', ['USER','MEMBER','VERIFIED_MEMBER','SELLER','ORG_ADMIN','ORG_STAFF','MODERATOR','EDITOR','SUPER_ADMIN']);
export const status = pgEnum('record_status', ['DRAFT','PENDING','ACTIVE','SUSPENDED','ARCHIVED']);
export const trust = pgEnum('trust_level', ['OFFICIAL_VERIFIED','INSTITUTION_VERIFIED','DUTA_VERIFIED','COMMUNITY_VERIFIED','USER_GENERATED']);
export const orgRole = pgEnum('organization_role', ['OWNER','ADMIN','SECRETARY','TREASURER','STAFF','MEMBER']);
export const entityType = pgEnum('entity_type', ['business','community','organisation']);
export const legalStatus = pgEnum('legal_status', ['registered','registered_under_other_law','foreign_registered','registration_pending','registration_not_verified','informal_group','unknown']);
export const presenceStatus = pgEnum('presence_status', ['pending','verified','failed','expired','revoked']);
export const presenceMethod = pgEnum('presence_method', ['malaysian_phone','device_location','manual_review','provider_assertion']);
export const responsiblePersonStatus = pgEnum('responsible_person_status', ['pending','active','inactive','revoked']);
export const verificationType = pgEnum('verification_type', ['phone','identity','liveness','malaysia_presence','entity_registration','representative_authority','licence','official_source']);
export const verificationStatus = pgEnum('verification_status', ['not_started','pending','verified','rejected','expired','revoked','suspended']);
export const verificationSource = pgEnum('verification_source', ['user_submitted','manual_review','official_registry','provider_assertion','system_check','admin_review']);
export const eligibilityType = pgEnum('eligibility_type', ['commercial','employer','paid_event','regulated_service','payment_connect']);
export const eligibilityStatus = pgEnum('eligibility_status', ['not_started','pending','approved','rejected','expired','suspended']);
export const eligibilityDecisionSource = pgEnum('eligibility_decision_source', ['manual_review','system_rule','regulatory_check','admin_review','legacy_migration']);
export const communityAccessScope = pgEnum('community_access_scope', ['malaysia_present_only','pre_arrival_allowed','global']);
export const membershipGeography = pgEnum('membership_geography', ['malaysia_present_only','malaysia_and_indonesia','global']);
export const organizationMembershipApplicationStatus = pgEnum('organization_membership_application_status', ['pending','approved','rejected','withdrawn','cancelled']);
export const organizationMembershipApplicationSource = pgEnum('organization_membership_application_source', ['direct_application','invite','referral','event','admin_added','legacy']);
export const marketplaceRiskTier = pgEnum('marketplace_risk_tier', ['GREEN','YELLOW','RED']);
export const marketplaceComplianceReviewStatus = pgEnum('marketplace_compliance_review_status', ['not_required','pending','approved','rejected','not_applicable']);
export const platformRole = pgEnum('platform_role', ['super_admin','compliance_admin','verification_reviewer','moderation_admin']);
export const eventRiskTier = pgEnum('event_risk_tier', ['LOW','REVIEW','PROHIBITED']);
export const eventComplianceReviewStatus = pgEnum('event_compliance_review_status', ['not_required','pending','approved','rejected','not_applicable']);
export const externalJobSourceType = pgEnum('external_job_source_type', ['OFFICIAL','DIRECT_EMPLOYER','LICENSED_APS']);
export const externalJobSourceStatus = pgEnum('external_job_source_status', ['active','stale','unknown','closed']);
export const moderationCaseStatus = pgEnum('moderation_case_status', ['NORMAL','LIMITED','UNDER_REVIEW','SUSPENDED','BANNED','REGULATORY_HOLD','CLOSED']);
export const moderationSeverity = pgEnum('moderation_severity', ['LOW','MEDIUM','HIGH','CRITICAL']);
export const moderationScope = pgEnum('moderation_scope', ['CONTENT_ONLY','MARKETPLACE','EVENTS','JOBS','COMMUNITY_POSTING','ENTITY_ACTIVITY','ACCOUNT']);

const audit = {
  createdAt: timestamp('created_at', { withTimezone:true }).defaultNow().notNull(),
  updatedAt: timestamp('updated_at', { withTimezone:true }).defaultNow().notNull(),
};
export const users = pgTable('users', {
  id: uuid('id').defaultRandom().primaryKey(), email:text('email').notNull(), passwordHash:text('password_hash'),
  name:text('name').notNull(), phone:text('phone'), avatarUrl:text('avatar_url'), city:text('city'), state:text('state'),
  hometown:text('hometown'), profession:text('profession'), interests:text('interests').array(), role:userRole('role').default('USER').notNull(),
  emailVerifiedAt:timestamp('email_verified_at',{withTimezone:true}), profileVisibility:text('profile_visibility').default('PRIVATE').notNull(),
  locationVisibility:text('location_visibility').default('PRIVATE').notNull(), suspendedAt:timestamp('suspended_at',{withTimezone:true}), ...audit,
}, t=>[uniqueIndex('users_email_uq').on(t.email), index('users_location_idx').on(t.state,t.city)]);
export const userPlatformRoles = pgTable('user_platform_roles',{id:uuid('id').defaultRandom().primaryKey(),userId:uuid('user_id').references(()=>users.id,{onDelete:'cascade'}).notNull(),role:platformRole('role').notNull(),assignedBy:uuid('assigned_by').references(()=>users.id),assignedAt:timestamp('assigned_at',{withTimezone:true}).defaultNow().notNull(),revokedAt:timestamp('revoked_at',{withTimezone:true}),reason:text('reason')},t=>[uniqueIndex('user_platform_role_active_uq').on(t.userId,t.role).where(sql`revoked_at IS NULL`),index('user_platform_role_active_idx').on(t.userId,t.revokedAt)]);
export const sessions = pgTable('sessions', { id:uuid('id').defaultRandom().primaryKey(), userId:uuid('user_id').references(()=>users.id,{onDelete:'cascade'}).notNull(), tokenHash:text('token_hash').notNull(), expiresAt:timestamp('expires_at',{withTimezone:true}).notNull(), createdAt:timestamp('created_at',{withTimezone:true}).defaultNow().notNull() },t=>[uniqueIndex('session_token_uq').on(t.tokenHash),index('session_user_idx').on(t.userId)]);
export const memberships = pgTable('memberships',{ id:uuid('id').defaultRandom().primaryKey(),userId:uuid('user_id').references(()=>users.id,{onDelete:'cascade'}).notNull(),plan:text('plan').notNull(),status:text('status').notNull(),priceMyr:numeric('price_myr',{precision:10,scale:2}),startDate:timestamp('start_date',{withTimezone:true}),renewalDate:timestamp('renewal_date',{withTimezone:true}),cancelledAt:timestamp('cancelled_at',{withTimezone:true}),eastelBonusStatus:text('eastel_bonus_status').default('NOT_CLAIMED'),...audit});
export const entities = pgTable('entities',{id:uuid('id').defaultRandom().primaryKey(),entityType:entityType('entity_type').notNull(),displayName:text('display_name').notNull(),slug:text('slug').notNull(),ownerUserId:uuid('owner_user_id').references(()=>users.id),recordStatus:status('record_status').default('PENDING').notNull(),legalStatus:legalStatus('legal_status').default('unknown').notNull(),legalStatusClaim:legalStatus('legal_status_claim'),legalStatusVerified:legalStatus('legal_status_verified'),registrationAuthority:text('registration_authority'),registrationType:text('registration_type'),registrationNumber:text('registration_number'),jurisdiction:text('jurisdiction'),operatingCountry:text('operating_country'),...audit},t=>[uniqueIndex('entities_slug_uq').on(t.slug),index('entities_type_idx').on(t.entityType),index('entities_owner_idx').on(t.ownerUserId),index('entities_legal_status_idx').on(t.legalStatus)]);
export const userPresenceChecks = pgTable('user_presence_checks',{id:uuid('id').defaultRandom().primaryKey(),userId:uuid('user_id').references(()=>users.id,{onDelete:'cascade'}).notNull(),countryCode:text('country_code').notNull(),status:presenceStatus('status').default('pending').notNull(),method:presenceMethod('method').notNull(),checkedAt:timestamp('checked_at',{withTimezone:true}),expiresAt:timestamp('expires_at',{withTimezone:true}),...audit},t=>[index('presence_user_idx').on(t.userId,t.status),index('presence_expiry_idx').on(t.expiresAt)]);
export const entityResponsiblePersons = pgTable('entity_responsible_persons',{id:uuid('id').defaultRandom().primaryKey(),entityId:uuid('entity_id').references(()=>entities.id,{onDelete:'cascade'}).notNull(),userId:uuid('user_id').references(()=>users.id,{onDelete:'cascade'}).notNull(),role:text('role').notNull(),status:responsiblePersonStatus('status').default('pending').notNull(),isPrimary:boolean('is_primary').default(false).notNull(),appointedAt:timestamp('appointed_at',{withTimezone:true}),endedAt:timestamp('ended_at',{withTimezone:true}),...audit},t=>[index('responsible_entity_idx').on(t.entityId,t.status),index('responsible_user_idx').on(t.userId,t.status),uniqueIndex('responsible_primary_active_uq').on(t.entityId).where(sql`is_primary = true AND status = 'active'`)]);
export const userVerifications = pgTable('user_verifications',{id:uuid('id').defaultRandom().primaryKey(),userId:uuid('user_id').references(()=>users.id,{onDelete:'cascade'}).notNull(),verificationType:verificationType('verification_type').notNull(),status:verificationStatus('status').default('not_started').notNull(),source:verificationSource('source').notNull(),checkedAt:timestamp('checked_at',{withTimezone:true}),recheckAt:timestamp('recheck_at',{withTimezone:true}),expiresAt:timestamp('expires_at',{withTimezone:true}),reviewedBy:uuid('reviewed_by').references(()=>users.id),...audit},t=>[index('user_verification_subject_idx').on(t.userId,t.verificationType,t.status)]);
export const entityVerifications = pgTable('entity_verifications',{id:uuid('id').defaultRandom().primaryKey(),entityId:uuid('entity_id').references(()=>entities.id,{onDelete:'cascade'}).notNull(),verificationType:verificationType('verification_type').notNull(),status:verificationStatus('status').default('not_started').notNull(),source:verificationSource('source').notNull(),checkedAt:timestamp('checked_at',{withTimezone:true}),recheckAt:timestamp('recheck_at',{withTimezone:true}),expiresAt:timestamp('expires_at',{withTimezone:true}),reviewedBy:uuid('reviewed_by').references(()=>users.id),...audit},t=>[index('entity_verification_subject_idx').on(t.entityId,t.verificationType,t.status)]);
export const verificationEvidence = pgTable('verification_evidence',{id:uuid('id').defaultRandom().primaryKey(),userVerificationId:uuid('user_verification_id').references(()=>userVerifications.id,{onDelete:'cascade'}),entityVerificationId:uuid('entity_verification_id').references(()=>entityVerifications.id,{onDelete:'cascade'}),providerReference:text('provider_reference'),documentMetadata:jsonb('document_metadata').$type<Record<string,unknown>>().default({}).notNull(),reviewNotes:text('review_notes'),...audit},t=>[index('verification_evidence_user_idx').on(t.userVerificationId),index('verification_evidence_entity_idx').on(t.entityVerificationId)]);
export const entityEligibilities = pgTable('entity_eligibilities',{id:uuid('id').defaultRandom().primaryKey(),entityId:uuid('entity_id').references(()=>entities.id,{onDelete:'cascade'}).notNull(),eligibilityType:eligibilityType('eligibility_type').notNull(),status:eligibilityStatus('status').default('not_started').notNull(),decisionSource:eligibilityDecisionSource('decision_source').notNull(),approvedAt:timestamp('approved_at',{withTimezone:true}),recheckAt:timestamp('recheck_at',{withTimezone:true}),expiresAt:timestamp('expires_at',{withTimezone:true}),reviewedBy:uuid('reviewed_by').references(()=>users.id),decisionReason:text('decision_reason'),...audit},t=>[uniqueIndex('entity_eligibility_current_uq').on(t.entityId,t.eligibilityType),index('entity_eligibility_status_idx').on(t.entityId,t.status)]);
export const organizations = pgTable('organizations',{id:uuid('id').defaultRandom().primaryKey(),entityId:uuid('entity_id').references(()=>entities.id),name:text('name').notNull(),type:text('type').notNull(),description:text('description'),state:text('state'),city:text('city'),logoUrl:text('logo_url'),contact:text('contact'),verification:trust('verification').default('USER_GENERATED').notNull(),recordStatus:status('status').default('PENDING').notNull(),membershipGeography:membershipGeography('membership_geography'),...audit},t=>[uniqueIndex('organizations_entity_uq').on(t.entityId)]);
export const organizationMembers = pgTable('organization_members',{organizationId:uuid('organization_id').references(()=>organizations.id,{onDelete:'cascade'}).notNull(),userId:uuid('user_id').references(()=>users.id,{onDelete:'cascade'}).notNull(),role:orgRole('role').default('MEMBER').notNull(),memberStatus:text('member_status').default('ACTIVE').notNull(),joinedAt:timestamp('joined_at',{withTimezone:true}).defaultNow().notNull()},t=>[uniqueIndex('org_member_uq').on(t.organizationId,t.userId)]);
export const organizationMembershipApplications = pgTable('organization_membership_applications',{id:uuid('id').defaultRandom().primaryKey(),organizationId:uuid('organization_id').references(()=>organizations.id,{onDelete:'cascade'}).notNull(),userId:uuid('user_id').references(()=>users.id,{onDelete:'cascade'}).notNull(),membershipType:text('membership_type').default('standard').notNull(),status:organizationMembershipApplicationStatus('status').default('pending').notNull(),source:organizationMembershipApplicationSource('source').default('direct_application').notNull(),applicationAnswers:jsonb('application_answers').$type<Record<string,unknown>>().default({}).notNull(),accessCountryCode:text('access_country_code'),submittedAt:timestamp('submitted_at',{withTimezone:true}).defaultNow().notNull(),reviewedAt:timestamp('reviewed_at',{withTimezone:true}),reviewedBy:uuid('reviewed_by').references(()=>users.id),decisionReason:text('decision_reason'),...audit},t=>[index('org_membership_application_org_status_idx').on(t.organizationId,t.status),index('org_membership_application_user_status_idx').on(t.userId,t.status),uniqueIndex('org_membership_application_pending_uq').on(t.organizationId,t.userId).where(sql`status = 'pending'`)]);
export const orgPermissions = pgTable('organization_permissions',{id:uuid('id').defaultRandom().primaryKey(),organizationId:uuid('organization_id').references(()=>organizations.id,{onDelete:'cascade'}).notNull(),role:orgRole('role').notNull(),permission:text('permission').notNull()},t=>[uniqueIndex('org_permission_uq').on(t.organizationId,t.role,t.permission)]);
export const officialSources = pgTable('official_sources',{id:uuid('id').defaultRandom().primaryKey(),institution:text('institution').notNull(),channel:text('channel').notNull(),url:text('url').notNull(),category:text('category').notNull(),priority:text('priority').notNull(),trustLevel:trust('trust_level').default('OFFICIAL_VERIFIED').notNull(),lastChecked:timestamp('last_checked',{withTimezone:true}).notNull(),checksum:text('checksum'),active:boolean('active').default(true).notNull(),...audit},t=>[uniqueIndex('sources_url_uq').on(t.url),index('source_institution_idx').on(t.institution)]);
export const contents = pgTable('contents',{id:uuid('id').defaultRandom().primaryKey(),authorId:uuid('author_id').references(()=>users.id),title:text('title').notNull(),slug:text('slug').notNull(),body:text('body').notNull(),type:text('type').notNull(),category:text('category'),state:text('state'),city:text('city'),trustLevel:trust('trust_level').default('USER_GENERATED').notNull(),sourceId:uuid('source_id').references(()=>officialSources.id),recordStatus:status('status').default('DRAFT').notNull(),publishedAt:timestamp('published_at',{withTimezone:true}),...audit},t=>[uniqueIndex('content_slug_uq').on(t.slug)]);
export const jobs = pgTable('jobs',{id:uuid('id').defaultRandom().primaryKey(),ownerId:uuid('owner_id').references(()=>users.id),employerEntityId:uuid('employer_entity_id').references(()=>entities.id),postingKind:text('posting_kind'),employerEligibilitySnapshot:text('employer_eligibility_snapshot'),publishedAt:timestamp('published_at',{withTimezone:true}),title:text('title').notNull(),employer:text('employer').notNull(),description:text('description').notNull(),state:text('state'),city:text('city'),salaryText:text('salary_text'),employmentType:text('employment_type').notNull(),requirements:text('requirements'),language:text('language'),applicationMethod:text('application_method'),trustLevel:trust('trust_level').default('USER_GENERATED').notNull(),expiresAt:timestamp('expires_at',{withTimezone:true}),recordStatus:status('status').default('PENDING').notNull(),...audit},t=>[index('jobs_search_idx').on(t.state,t.city,t.employmentType),index('jobs_employer_entity_idx').on(t.employerEntityId,t.recordStatus)]);
export const externalJobListings = pgTable('external_job_listings',{id:uuid('id').defaultRandom().primaryKey(),externalJobId:text('external_job_id').notNull(),sourceType:externalJobSourceType('source_type').notNull(),sourceName:text('source_name').notNull(),sourceUrl:text('source_url').notNull(),destinationCountry:text('destination_country').notNull(),jobTitle:text('job_title').notNull(),sector:text('sector'),employerName:text('employer_name'),p3miName:text('p3mi_name'),location:text('location'),vacancyCount:integer('vacancy_count'),educationRequirement:text('education_requirement'),publishedAt:timestamp('published_at',{withTimezone:true}),expiresAt:timestamp('expires_at',{withTimezone:true}),sourceStatus:externalJobSourceStatus('source_status').default('unknown').notNull(),fetchedAt:timestamp('fetched_at',{withTimezone:true}),lastCheckedAt:timestamp('last_checked_at',{withTimezone:true}),...audit},t=>[uniqueIndex('external_job_source_id_uq').on(t.sourceType,t.externalJobId),index('external_jobs_malaysia_active_idx').on(t.destinationCountry,t.sourceStatus,t.lastCheckedAt)]);
export const sellers = pgTable('sellers',{id:uuid('id').defaultRandom().primaryKey(),userId:uuid('user_id').references(()=>users.id),organizationId:uuid('organization_id').references(()=>organizations.id),entityId:uuid('entity_id').references(()=>entities.id),name:text('name').notNull(),description:text('description'),trustLevel:trust('trust_level').default('USER_GENERATED').notNull(),recordStatus:status('status').default('PENDING').notNull(),...audit});
export const products = pgTable('products',{id:uuid('id').defaultRandom().primaryKey(),sellerId:uuid('seller_id').references(()=>sellers.id,{onDelete:'cascade'}).notNull(),sellerEntityId:uuid('seller_entity_id').references(()=>entities.id),name:text('name').notNull(),description:text('description').notNull(),category:text('category').notNull(),riskTier:marketplaceRiskTier('risk_tier'),commercialEligibilitySnapshot:text('commercial_eligibility_snapshot'),complianceReviewStatus:marketplaceComplianceReviewStatus('compliance_review_status'),publishedAt:timestamp('published_at',{withTimezone:true}),priceMyr:numeric('price_myr',{precision:12,scale:2}),images:jsonb('images').$type<string[]>().default([]),state:text('state'),city:text('city'),recordStatus:status('status').default('PENDING').notNull(),...audit});
export const events = pgTable('events',{id:uuid('id').defaultRandom().primaryKey(),organizationId:uuid('organization_id').references(()=>organizations.id,{onDelete:'cascade'}),organizerEntityId:uuid('organizer_entity_id').references(()=>entities.id),title:text('title').notNull(),description:text('description'),location:text('location'),startsAt:timestamp('starts_at',{withTimezone:true}).notNull(),capacity:integer('capacity'),registrationEnabled:boolean('registration_enabled').default(true),priceMyr:numeric('price_myr',{precision:10,scale:2}),eventCategory:text('event_category'),riskTier:eventRiskTier('risk_tier'),complianceReviewStatus:eventComplianceReviewStatus('compliance_review_status'),publishedAt:timestamp('published_at',{withTimezone:true}),recordStatus:status('status').default('DRAFT').notNull(),...audit});
export const orgFinances = pgTable('organization_finances',{id:uuid('id').defaultRandom().primaryKey(),organizationId:uuid('organization_id').references(()=>organizations.id,{onDelete:'cascade'}).notNull(),actorId:uuid('actor_id').references(()=>users.id).notNull(),type:text('type').notNull(),amount:numeric('amount',{precision:14,scale:2}).notNull(),description:text('description').notNull(),transactionAt:timestamp('transaction_at',{withTimezone:true}).notNull(),...audit},t=>[index('finance_org_idx').on(t.organizationId,t.transactionAt)]);
export const communities = pgTable('communities',{id:uuid('id').defaultRandom().primaryKey(),entityId:uuid('entity_id').references(()=>entities.id),ownerId:uuid('owner_id').references(()=>users.id),name:text('name').notNull(),description:text('description'),category:text('category').notNull(),state:text('state'),city:text('city'),visibility:text('visibility').default('PUBLIC').notNull(),trustLevel:trust('trust_level').default('USER_GENERATED').notNull(),recordStatus:status('record_status').default('PENDING').notNull(),communityAccessScope:communityAccessScope('community_access_scope'),...audit},t=>[index('community_location_idx').on(t.state,t.city,t.category),uniqueIndex('communities_entity_uq').on(t.entityId)]);
export const communityMembers = pgTable('community_members',{communityId:uuid('community_id').references(()=>communities.id,{onDelete:'cascade'}).notNull(),userId:uuid('user_id').references(()=>users.id,{onDelete:'cascade'}).notNull(),role:text('role').default('MEMBER').notNull(),joinedAt:timestamp('joined_at',{withTimezone:true}).defaultNow().notNull()},t=>[uniqueIndex('community_member_uq').on(t.communityId,t.userId)]);
export const organizationDocuments = pgTable('organization_documents',{id:uuid('id').defaultRandom().primaryKey(),organizationId:uuid('organization_id').references(()=>organizations.id,{onDelete:'cascade'}).notNull(),authorId:uuid('author_id').references(()=>users.id).notNull(),type:text('type').notNull(),title:text('title').notNull(),storageKey:text('storage_key'),content:text('content'),recordStatus:status('status').default('DRAFT').notNull(),...audit},t=>[index('org_document_idx').on(t.organizationId,t.type)]);
export const organizationMeetings = pgTable('organization_meetings',{id:uuid('id').defaultRandom().primaryKey(),organizationId:uuid('organization_id').references(()=>organizations.id,{onDelete:'cascade'}).notNull(),title:text('title').notNull(),agenda:text('agenda'),minutes:text('minutes'),startsAt:timestamp('starts_at',{withTimezone:true}).notNull(),location:text('location'),recordStatus:status('status').default('DRAFT').notNull(),...audit});
export const organizationLetters = pgTable('organization_letters',{id:uuid('id').defaultRandom().primaryKey(),organizationId:uuid('organization_id').references(()=>organizations.id,{onDelete:'cascade'}).notNull(),number:text('number'),direction:text('direction').notNull(),title:text('title').notNull(),content:text('content'),approvalStatus:text('approval_status').default('DRAFT').notNull(),approvedBy:uuid('approved_by').references(()=>users.id),...audit},t=>[index('org_letter_idx').on(t.organizationId,t.direction)]);
export const payments = pgTable('payments',{id:uuid('id').defaultRandom().primaryKey(),membershipId:uuid('membership_id').references(()=>memberships.id,{onDelete:'cascade'}).notNull(),provider:text('provider').notNull(),providerReference:text('provider_reference'),amountMyr:numeric('amount_myr',{precision:10,scale:2}).notNull(),status:text('status').notNull(),invoiceNumber:text('invoice_number'),failureCode:text('failure_code'),paidAt:timestamp('paid_at',{withTimezone:true}),...audit},t=>[uniqueIndex('payment_provider_ref_uq').on(t.provider,t.providerReference)]);
export const notifications = pgTable('notifications',{id:uuid('id').defaultRandom().primaryKey(),userId:uuid('user_id').references(()=>users.id,{onDelete:'cascade'}).notNull(),type:text('type').notNull(),priority:text('priority').notNull(),title:text('title').notNull(),body:text('body').notNull(),readAt:timestamp('read_at',{withTimezone:true}),createdAt:timestamp('created_at',{withTimezone:true}).defaultNow().notNull()},t=>[index('notification_user_idx').on(t.userId,t.readAt)]);
export const organizationSubscriptions = pgTable('organization_subscriptions',{id:uuid('id').defaultRandom().primaryKey(),organizationId:uuid('organization_id').references(()=>organizations.id,{onDelete:'cascade'}).notNull(),plan:text('plan').default('FREE').notNull(),status:text('status').default('ACTIVE').notNull(),priceMyr:numeric('price_myr',{precision:10,scale:2}).default('0').notNull(),provider:text('provider'),providerReference:text('provider_reference'),startDate:timestamp('start_date',{withTimezone:true}).defaultNow().notNull(),renewalDate:timestamp('renewal_date',{withTimezone:true}),cancelledAt:timestamp('cancelled_at',{withTimezone:true}),graceEndsAt:timestamp('grace_ends_at',{withTimezone:true}),...audit},t=>[uniqueIndex('org_subscription_org_uq').on(t.organizationId)]);
export const organizationPayments = pgTable('organization_payments',{id:uuid('id').defaultRandom().primaryKey(),subscriptionId:uuid('subscription_id').references(()=>organizationSubscriptions.id,{onDelete:'cascade'}).notNull(),provider:text('provider').notNull(),providerReference:text('provider_reference'),amountMyr:numeric('amount_myr',{precision:10,scale:2}).notNull(),status:text('status').notNull(),invoiceNumber:text('invoice_number'),failureCode:text('failure_code'),paidAt:timestamp('paid_at',{withTimezone:true}),...audit},t=>[uniqueIndex('org_payment_provider_ref_uq').on(t.provider,t.providerReference)]);
export const organizationBranches = pgTable('organization_branches',{id:uuid('id').defaultRandom().primaryKey(),organizationId:uuid('organization_id').references(()=>organizations.id,{onDelete:'cascade'}).notNull(),name:text('name').notNull(),state:text('state'),city:text('city'),contact:text('contact'),active:boolean('active').default(true).notNull(),...audit},t=>[index('org_branch_idx').on(t.organizationId,t.active)]);
export const organizationAttendance = pgTable('organization_attendance',{id:uuid('id').defaultRandom().primaryKey(),organizationId:uuid('organization_id').references(()=>organizations.id,{onDelete:'cascade'}).notNull(),eventId:uuid('event_id').references(()=>events.id,{onDelete:'cascade'}),meetingId:uuid('meeting_id').references(()=>organizationMeetings.id,{onDelete:'cascade'}),userId:uuid('user_id').references(()=>users.id,{onDelete:'cascade'}).notNull(),status:text('status').notNull(),checkedInAt:timestamp('checked_in_at',{withTimezone:true}),createdAt:timestamp('created_at',{withTimezone:true}).defaultNow().notNull()},t=>[uniqueIndex('org_attendance_uq').on(t.organizationId,t.eventId,t.meetingId,t.userId)]);
export const organizationTasks = pgTable('organization_tasks',{id:uuid('id').defaultRandom().primaryKey(),organizationId:uuid('organization_id').references(()=>organizations.id,{onDelete:'cascade'}).notNull(),assigneeId:uuid('assignee_id').references(()=>users.id),createdBy:uuid('created_by').references(()=>users.id).notNull(),title:text('title').notNull(),description:text('description'),dueAt:timestamp('due_at',{withTimezone:true}),status:text('status').default('OPEN').notNull(),...audit},t=>[index('org_task_idx').on(t.organizationId,t.status)]);
export const publicationTemplates = pgTable('publication_templates',{id:uuid('id').defaultRandom().primaryKey(),organizationId:uuid('organization_id').references(()=>organizations.id,{onDelete:'cascade'}),name:text('name').notNull(),type:text('type').notNull(),category:text('category').notNull(),schema:jsonb('schema').$type<Record<string,unknown>>().notNull(),active:boolean('active').default(true).notNull(),createdBy:uuid('created_by').references(()=>users.id),...audit},t=>[index('publication_template_idx').on(t.organizationId,t.type,t.active)]);
export const publicationProjects = pgTable('publication_projects',{id:uuid('id').defaultRandom().primaryKey(),organizationId:uuid('organization_id').references(()=>organizations.id,{onDelete:'cascade'}).notNull(),createdBy:uuid('created_by').references(()=>users.id).notNull(),approvedBy:uuid('approved_by').references(()=>users.id),type:text('type').notNull(),title:text('title').notNull(),prompt:text('prompt'),content:jsonb('content').$type<Record<string,unknown>>().notNull(),status:text('status').default('DRAFT').notNull(),publishedAt:timestamp('published_at',{withTimezone:true}),...audit},t=>[index('publication_project_idx').on(t.organizationId,t.status,t.type)]);
export const meetingTranscripts = pgTable('meeting_transcripts',{id:uuid('id').defaultRandom().primaryKey(),organizationId:uuid('organization_id').references(()=>organizations.id,{onDelete:'cascade'}).notNull(),meetingId:uuid('meeting_id').references(()=>organizationMeetings.id,{onDelete:'cascade'}).notNull(),createdBy:uuid('created_by').references(()=>users.id).notNull(),language:text('language').default('id').notNull(),transcript:text('transcript').notNull(),summary:text('summary').notNull(),actionItems:jsonb('action_items').$type<string[]>().default([]).notNull(),consentConfirmed:boolean('consent_confirmed').default(false).notNull(),audioDeletedAt:timestamp('audio_deleted_at',{withTimezone:true}).notNull(),approvedAt:timestamp('approved_at',{withTimezone:true}),...audit},t=>[uniqueIndex('meeting_transcript_meeting_uq').on(t.meetingId)]);
export const officialOffices = pgTable('official_offices',{id:text('id').primaryKey(),institution:text('institution').notNull(),city:text('city').notNull(),region:text('region').notNull(),latitude:numeric('latitude',{precision:9,scale:6}).notNull(),longitude:numeric('longitude',{precision:9,scale:6}).notNull(),officialUrl:text('official_url').notNull(),sourceChannel:text('source_channel').notNull(),lastChecked:timestamp('last_checked',{withTimezone:true}).notNull(),active:boolean('active').default(true).notNull(),...audit});
export const officialContacts = pgTable('official_contacts',{id:text('id').primaryKey(),officeId:text('office_id').references(()=>officialOffices.id,{onDelete:'cascade'}).notNull(),label:text('label').notNull(),displayNumber:text('display_number').notNull(),e164:text('e164').notNull(),channel:text('channel').notNull(),purpose:text('purpose').notNull(),warning:text('warning'),whatsappConfirmed:boolean('whatsapp_confirmed').default(false).notNull(),active:boolean('active').default(true).notNull(),lastChecked:timestamp('last_checked',{withTimezone:true}).notNull(),...audit},t=>[index('official_contact_office_idx').on(t.officeId,t.active)]);
export const officialEvidence = pgTable('official_evidence',{id:uuid('id').defaultRandom().primaryKey(),officeId:text('office_id').references(()=>officialOffices.id,{onDelete:'set null'}),institution:text('institution').notNull(),evidenceType:text('evidence_type').notNull(),filePath:text('file_path').notNull(),capturedAt:timestamp('captured_at',{withTimezone:true}).notNull(),effectiveDate:timestamp('effective_date',{withTimezone:true}),verificationStatus:text('verification_status').default('SUPPLIED_OFFICIAL_SCREENSHOT').notNull(),extractedData:jsonb('extracted_data').$type<Record<string,unknown>>().default({}).notNull(),...audit},t=>[uniqueIndex('official_evidence_path_uq').on(t.filePath),index('official_evidence_office_idx').on(t.officeId,t.evidenceType)]);
export const aiConversations = pgTable('ai_conversations',{id:uuid('id').defaultRandom().primaryKey(),userId:uuid('user_id').references(()=>users.id,{onDelete:'set null'}),intent:text('intent'),messages:jsonb('messages').notNull(),sourceIds:uuid('source_ids').array(),confidence:text('confidence'),createdAt:timestamp('created_at',{withTimezone:true}).defaultNow().notNull()});
export const reports = pgTable('reports',{id:uuid('id').defaultRandom().primaryKey(),reporterId:uuid('reporter_id').references(()=>users.id),entityType:text('entity_type').notNull(),entityId:uuid('entity_id').notNull(),category:text('category').notNull(),details:text('details'),status:text('status').default('OPEN').notNull(),...audit});
export const moderationCases = pgTable('moderation_cases',{id:uuid('id').defaultRandom().primaryKey(),targetType:text('target_type').notNull(),targetId:uuid('target_id').notNull(),status:moderationCaseStatus('status').default('UNDER_REVIEW').notNull(),severity:moderationSeverity('severity').default('LOW').notNull(),assignedReviewerId:uuid('assigned_reviewer_id').references(()=>users.id),decision:text('decision'),decisionReason:text('decision_reason'),decidedAt:timestamp('decided_at',{withTimezone:true}),reviewedBy:uuid('reviewed_by').references(()=>users.id),...audit},t=>[index('moderation_case_target_idx').on(t.targetType,t.targetId,t.status),index('moderation_case_reviewer_idx').on(t.assignedReviewerId,t.status)]);
export const moderationCaseReports = pgTable('moderation_case_reports',{caseId:uuid('case_id').references(()=>moderationCases.id,{onDelete:'cascade'}).notNull(),reportId:uuid('report_id').references(()=>reports.id,{onDelete:'restrict'}).notNull(),createdAt:timestamp('created_at',{withTimezone:true}).defaultNow().notNull()},t=>[uniqueIndex('moderation_case_report_uq').on(t.caseId,t.reportId)]);
export const moderationActions = pgTable('moderation_actions',{id:uuid('id').defaultRandom().primaryKey(),caseId:uuid('case_id').references(()=>moderationCases.id,{onDelete:'restrict'}).notNull(),actorUserId:uuid('actor_user_id').references(()=>users.id).notNull(),targetType:text('target_type').notNull(),targetId:uuid('target_id').notNull(),scope:moderationScope('scope').notNull(),oldStatus:moderationCaseStatus('old_status'),newStatus:moderationCaseStatus('new_status').notNull(),reason:text('reason').notNull(),createdAt:timestamp('created_at',{withTimezone:true}).defaultNow().notNull()},t=>[index('moderation_action_case_idx').on(t.caseId,t.createdAt),index('moderation_action_target_idx').on(t.targetType,t.targetId,t.createdAt)]);
export const moderationEvidence = pgTable('moderation_evidence',{id:uuid('id').defaultRandom().primaryKey(),caseId:uuid('case_id').references(()=>moderationCases.id,{onDelete:'cascade'}).notNull(),submittedBy:uuid('submitted_by').references(()=>users.id),storageKey:text('storage_key'),note:text('note'),createdAt:timestamp('created_at',{withTimezone:true}).defaultNow().notNull()},t=>[index('moderation_evidence_case_idx').on(t.caseId,t.createdAt)]);
export const auditLogs = pgTable('audit_logs',{id:uuid('id').defaultRandom().primaryKey(),actorId:uuid('actor_id').references(()=>users.id),organizationId:uuid('organization_id').references(()=>organizations.id),action:text('action').notNull(),entityType:text('entity_type').notNull(),entityId:text('entity_id'),metadata:jsonb('metadata'),ipHash:text('ip_hash'),createdAt:timestamp('created_at',{withTimezone:true}).defaultNow().notNull()},t=>[index('audit_actor_idx').on(t.actorId,t.createdAt)]);
export const aiTelemetryEvents = pgTable('ai_telemetry_events',{id:uuid('id').defaultRandom().primaryKey(),userRef:uuid('user_ref').references(()=>users.id),intent:text('intent').notNull(),risk:text('risk').notNull(),sensitivity:text('sensitivity').notNull(),modelClass:text('model_class').notNull(),provider:text('provider'),model:text('model'),sourceRequirement:text('source_requirement').notNull(),sourceTier:text('source_tier'),quotaOutcome:text('quota_outcome').notNull(),weightedUnits:integer('weighted_units').notNull(),inputTokens:integer('input_tokens').notNull(),outputTokens:integer('output_tokens').notNull(),estimatedCost:numeric('estimated_cost',{precision:14,scale:8}).notNull(),latencyMs:integer('latency_ms').notNull(),success:boolean('success').notNull(),errorCode:text('error_code'),fallbackUsed:boolean('fallback_used').notNull(),createdAt:timestamp('created_at',{withTimezone:true}).defaultNow().notNull()},t=>[index('ai_telemetry_events_user_created_idx').on(t.userRef,t.createdAt)]);

