[CmdletBinding()]
param([ValidateRange(1024,65535)][int]$LoopbackPort=56187)
Set-StrictMode -Version Latest; $ErrorActionPreference='Stop'
$docker='C:\Users\User\AppData\Local\Programs\DockerDesktop\resources\bin\docker.exe'; $name='duta-local-test-db-0045'; $db='duta_local_test_0045'; $root=Split-Path -Parent $PSScriptRoot; $created=$false
function Invoke-SqlFile([string]$file) { & $docker exec -i --user postgres $name psql -v ON_ERROR_STOP=1 -U postgres -d $db -f "/repo/$file"; if($LASTEXITCODE){throw "psql failed: $file"} }
try {
 & $docker run -d --rm --name $name -v "${root}:/repo:ro" -p "127.0.0.1:${LoopbackPort}:5432" -e POSTGRES_PASSWORD=local -e POSTGRES_DB=$db postgres:16-alpine | Out-Null; $created=$true
 $stable=0; for($i=0;$i -lt 60;$i++){& $docker inspect -f '{{.State.Running}}' $name 1>$null 2>$null; $running=$LASTEXITCODE -eq 0; & $docker exec $name pg_isready -U postgres -d $db 1>$null 2>$null; if($running -and $LASTEXITCODE -eq 0){$stable++; if($stable -ge 3){break}}else{$stable=0}; Start-Sleep 1}; if($stable -lt 3){throw 'disposable PostgreSQL did not reach stable final-server readiness'}
 $pre="CREATE EXTENSION pgcrypto; CREATE ROLE anon NOLOGIN; CREATE ROLE authenticated NOLOGIN; CREATE ROLE duta_app NOLOGIN NOBYPASSRLS; CREATE TYPE public.user_role AS ENUM ('EDITOR','MODERATOR','SUPER_ADMIN','USER'); CREATE TYPE public.source_purpose AS ENUM ('NEWS','CONSULAR_SERVICE','CONTACT'); CREATE TYPE public.trust_level AS ENUM ('OFFICIAL_VERIFIED'); CREATE TABLE public.users(id uuid primary key,role public.user_role not null,suspended_at timestamptz); CREATE TABLE public.official_sources(id uuid primary key default gen_random_uuid(),institution text not null,channel text not null,url text not null,category text not null,priority text not null,trust_level public.trust_level not null default 'OFFICIAL_VERIFIED',last_checked timestamptz not null default now(),active boolean not null default true,source_purpose public.source_purpose,checksum text,updated_at timestamptz); CREATE TABLE public.official_source_governance(source_id uuid primary key references public.official_sources(id)); CREATE FUNCTION public.current_app_user_id() RETURNS uuid LANGUAGE sql STABLE SECURITY DEFINER SET search_path='' AS 'SELECT nullif(current_setting(''app.user_id'',true),'''')::uuid'; CREATE FUNCTION public.current_app_has_role(allowed public.user_role[]) RETURNS boolean LANGUAGE sql STABLE SECURITY DEFINER SET search_path='' AS 'SELECT EXISTS(SELECT 1 FROM public.users WHERE id=public.current_app_user_id() AND role=ANY(allowed) AND suspended_at IS NULL)'; GRANT USAGE ON SCHEMA public TO duta_app; GRANT EXECUTE ON FUNCTION public.current_app_user_id(),public.current_app_has_role(public.user_role[]) TO duta_app;"
 $pre | & $docker exec -i --user postgres $name psql -v ON_ERROR_STOP=1 -U postgres -d $db; if($LASTEXITCODE){throw 'prestate failed'}
 Invoke-SqlFile 'db/migrations/0045_official_news_editorial_foundation.sql'; Invoke-SqlFile 'tests/db/migrations/0045/verify.sql'; Invoke-SqlFile 'tests/db/migrations/0045/runtime-security.sql'; Invoke-SqlFile 'tests/db/migrations/0045/runtime-adversarial.sql'; Write-Output '0045_DISPOSABLE_VALIDATION=PASS'
} finally {if($created){& $docker rm -f $name 1>$null 2>$null}}
